const colors = {
  light: {
    text: '#1A1A2E',
    tint: '#1B3A6B',
    background: '#F7F3EC',
    foreground: '#1A1A2E',
    card: '#FFFFFF',
    cardForeground: '#1A1A2E',
    primary: '#1B3A6B',
    primaryForeground: '#FFFFFF',
    secondary: '#EDE8DF',
    secondaryForeground: '#1A1A2E',
    muted: '#EDE8DF',
    mutedForeground: '#8A8070',
    accent: '#C4922A',
    accentForeground: '#1A1A2E',
    destructive: '#D93025',
    destructiveForeground: '#FFFFFF',
    border: '#DDD8CE',
    input: '#DDD8CE',
    englishText: '#1B3A6B',
    portugueseText: '#3D6B41',
    verseNumber: '#C4922A',
  },
  dark: {
    text: '#EDE8DF',
    tint: '#7AAFDD',
    background: '#0D1B2A',
    foreground: '#EDE8DF',
    card: '#162235',
    cardForeground: '#EDE8DF',
    primary: '#5B9BD5',
    primaryForeground: '#0D1B2A',
    secondary: '#1E2D40',
    secondaryForeground: '#EDE8DF',
    muted: '#1E2D40',
    mutedForeground: '#8A9BAD',
    accent: '#C4922A',
    accentForeground: '#EDE8DF',
    destructive: '#E53E3E',
    destructiveForeground: '#FFFFFF',
    border: '#243347',
    input: '#243347',
    englishText: '#7AAFDD',
    portugueseText: '#7BB87F',
    verseNumber: '#C4922A',
  },
  radius: 12,
};

export default colors;
