import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: '1thessalonians',
  name: '1 Tessalonicenses',
  englishName: '1 Thessalonians',
  testament: 'new',
  chapters: {
    1: [
      { v: 1, en: 'Paul, Silvanus, and Timothy, to the assembly of the Thessalonians in God the Father and the Lord Jesus Christ: Grace to you and peace from God our Father and the Lord Jesus Christ.', pt: 'Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus Pai e no Senhor Jesus Cristo: Graça e paz vos sejam dadas.' },
      { v: 2, en: 'We always give thanks to God for all of you, mentioning you in our prayers,', pt: 'Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações,' },
      { v: 3, en: 'remembering without ceasing your work of faith and labor of love and perseverance of hope in our Lord Jesus Christ, before our God and Father.', pt: 'lembrando-nos sem cessar da vossa obra de fé, do vosso trabalho de amor e da vossa firmeza de esperança em nosso Senhor Jesus Cristo, diante de nosso Deus e Pai,' },
      { v: 4, en: 'We know, brothers loved by God, that you are chosen,', pt: 'conhecendo, irmãos, amados de Deus, a vossa eleição;' },
      { v: 5, en: 'and that our Good News came to you not in word only, but also in power, and in the Holy Spirit, and with much assurance. You know what kind of men we showed ourselves to be among you for your sake.', pt: 'porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espírito Santo e em plena convicção, como bem sabeis quais fomos entre vós por amor de vós.' },
      { v: 6, en: 'You became imitators of us, and of the Lord, having received the word in much affliction, with joy of the Holy Spirit,', pt: 'E vós vos tornastes imitadores nossos e do Senhor, tendo recebido a palavra em muita tribulação, com gozo do Espírito Santo.' },
      { v: 7, en: 'so that you became an example to all who believe in Macedonia and in Achaia.', pt: 'De sorte que vos tornastes modelo para todos os crentes na Macedônia e na Acaia.' },
      { v: 8, en: 'For from you the word of the Lord has been declared, not only in Macedonia and Achaia, but also in every place your faith toward God has gone out; so that we need not to say anything.', pt: 'Porque, partindo de vós fez-se ouvir a palavra do Senhor, não somente na Macedônia e na Acaia, mas também em todos os lugares a vossa fé para com Deus se divulgou, de tal maneira que não temos necessidade de falar coisa alguma;' },
      { v: 9, en: 'For they themselves report concerning us what kind of a reception we had from you; and how you turned to God from idols, to serve a living and true God,', pt: 'porque eles mesmos anunciam de nós qual a entrada que tivemos entre vós, e como vos convertestes dos ídolos a Deus, para servirdes ao Deus vivo e verdadeiro,' },
      { v: 10, en: 'and to wait for his Son from heaven, whom he raised from the dead—Jesus, who delivers us from the wrath to come.', pt: 'e esperardes dos céus a seu Filho, a quem ele ressuscitou dentre os mortos, a saber, Jesus, que nos livra da ira vindoura.' },
    ],
    2: [
      { v: 1, en: 'For you yourselves know, brothers, our visit to you wasn’t in vain,', pt: 'Porque vós mesmos sabeis, irmãos, que a nossa entrada entre vós não foi vã;' },
      { v: 2, en: 'but having suffered before and been shamefully treated, as you know, at Philippi, we grew bold in our God to tell you the Good News of God in much conflict.', pt: 'mas, havendo anteriormente padecido e sido maltratados em Filipos, como sabeis, tivemos a confiança em nosso Deus para vos falar o evangelho de Deus em meio de grande combate.' },
      { v: 3, en: 'For our exhortation is not of error, nor of uncleanness, nor in deception.', pt: 'Porque a nossa exortação não procede de erro, nem de imundícia, nem é feita com dolo;' },
      { v: 4, en: 'But even as we have been approved by God to be entrusted with the Good News, so we speak; not as pleasing men, but God, who tests our hearts.', pt: 'mas, assim como fomos aprovados por Deus para que o evangelho nos fosse confiado, assim falamos, não para agradar aos homens, mas a Deus, que prova os nossos corações.' },
      { v: 5, en: 'For neither were we at any time found using words of flattery, as you know, nor a cloak of covetousness (God is witness),', pt: 'Pois, nunca usamos de palavras lisonjeiras, como sabeis, nem agimos com intuitos gananciosos. Deus é testemunha,' },
      { v: 6, en: 'nor seeking glory from men (neither from you nor from others), when we might have claimed authority as apostles of Christ.', pt: 'nem buscamos glória de homens, quer de vós, quer de outros, embora pudéssemos, como apóstolos de Cristo, ser-vos pesados;' },
      { v: 7, en: 'But we were gentle among you, like a nursing mother cherishes her own children.', pt: 'antes nos apresentamos brandos entre vós, qual ama que acaricia seus próprios filhos.' },
      { v: 8, en: 'Even so, affectionately longing for you, we were well pleased to impart to you, not the Good News of God only, but also our own souls, because you had become very dear to us.', pt: 'Assim nós, sendo-vos tão afeiçoados, de boa vontade desejávamos comunicar-vos não somente o evangelho de Deus, mas ainda as nossas próprias almas; porquanto vos tornastes muito amados de nós.' },
      { v: 9, en: 'For you remember, brothers, our labor and travail; for working night and day, that we might not burden any of you, we preached to you the Good News of God.', pt: 'Porque vos lembrais, irmãos, do nosso labor e fadiga; pois, trabalhando noite e dia, para não sermos pesados a nenhum de vós, vos pregamos o evangelho de Deus.' },
      { v: 10, en: 'You are witnesses with God, how holy, righteously, and blamelessly we behaved ourselves toward you who believe.', pt: 'Vós e Deus sois testemunhas de quão santa e irrepreensivelmente nos portamos para convosco que credes;' },
      { v: 11, en: 'As you know, we exhorted, comforted, and implored every one of you, as a father does his own children,', pt: 'assim como sabeis de que modo vos tratávamos a cada um de vós, como um pai a seus filhos,' },
      { v: 12, en: 'to the end that you should walk worthily of God, who calls you into his own Kingdom and glory.', pt: 'exortando-vos e consolando-vos, e instando que andásseis de um modo digno de Deus, o qual vos chama ao seu reino e glória.' },
      { v: 13, en: 'For this cause we also thank God without ceasing, that, when you received from us the word of the message of God, you accepted it not as the word of men, but, as it is in truth, the word of God, which also works in you who believe.', pt: 'Por isso nós também, sem cessar, damos graças a Deus, porquanto vós, havendo recebido a palavra de Deus que de nós ouvistes, a recebestes, não como palavra de homens, mas (segundo ela é na verdade) como palavra de Deus, a qual também opera em vós que credes.' },
      { v: 14, en: 'For you, brothers, became imitators of the assemblies of God which are in Judea in Christ Jesus; for you also suffered the same things from your own countrymen, even as they did from the Jews;', pt: 'Pois vós, irmãos, vos haveis feito imitadores das igrejas de Deus em Cristo Jesus que estão na Judéia; porque também padecestes de vossos próprios concidadãos o mesmo que elas padeceram dos judeus;' },
      { v: 15, en: 'who killed both the Lord Jesus and their own prophets, and drove us out, and didn’t please God, and are contrary to all men;', pt: 'os quais mataram ao Senhor Jesus, bem como aos profetas, e a nós nos perseguiram, e não agradam a Deus, e são contrários a todos os homens,' },
      { v: 16, en: 'forbidding us to speak to the Gentiles that they may be saved; to fill up their sins always. But wrath has come on them to the uttermost.', pt: 'e nos impedem de falar aos gentios para que sejam salvos; de modo que enchem sempre a medida de seus pecados; mas a ira caiu sobre eles afinal.' },
      { v: 17, en: 'But we, brothers, being bereaved of you for a short season, in presence, not in heart, tried even harder to see your face with great desire,', pt: 'Nós, porém, irmãos, sendo privados de vós por algum tempo, de vista, mas não de coração, tanto mais procuramos com grande desejo ver o vosso rosto;' },
      { v: 18, en: 'because we wanted to come to you—indeed, I, Paul, once and again—but Satan hindered us.', pt: 'pelo que quisemos ir ter convosco, pelo menos eu, Paulo, não somente uma vez, mas duas, e Satanás nos impediu.' },
      { v: 19, en: 'For what is our hope, or joy, or crown of rejoicing? Isn’t it even you, before our Lord Jesus at his coming?', pt: 'Porque, qual é a nossa esperança, ou gozo, ou coroa de glória, diante de nosso Senhor Jesus na sua vinda? Porventura não o sois vós?' },
      { v: 20, en: 'For you are our glory and our joy.', pt: 'Na verdade vós sois a nossa glória e o nosso gozo.' },
    ],
    3: [
      { v: 1, en: 'Therefore when we couldn’t stand it any longer, we thought it good to be left behind at Athens alone,', pt: 'Pelo que, não podendo mais suportar o cuidado por vós, achamos por bem ficar sozinhos em Atenas,' },
      { v: 2, en: 'and sent Timothy, our brother and God’s servant in the Good News of Christ, to establish you, and to comfort you concerning your faith;', pt: 'e enviamos Timóteo, nosso irmão, e ministro de Deus no evangelho de Cristo, para vos fortalecer e vos exortar acerca da vossa fé;' },
      { v: 3, en: 'that no one be moved by these afflictions. For you know that we are appointed to this task.', pt: 'para que ninguém seja abalado por estas tribulações; porque vós mesmo sabeis que para isto fomos destinados;' },
      { v: 4, en: 'For most certainly, when we were with you, we told you beforehand that we are to suffer affliction, even as it happened, and you know.', pt: 'pois, quando estávamos ainda convosco, de antemão vos declarávamos que havíamos de padecer tribulações, como sucedeu, e vós o sabeis.' },
      { v: 5, en: 'For this cause I also, when I couldn’t stand it any longer, sent that I might know your faith, for fear that by any means the tempter had tempted you, and our labor would have been in vain.', pt: 'Por isso também, não podendo eu esperar mais, mandei saber da vossa fé, receando que o tentador vos tivesse tentado, e o nosso trabalho se houvesse tornado inútil.' },
      { v: 6, en: 'But when Timothy came just now to us from you, and brought us glad news of your faith and love, and that you have good memories of us always, longing to see us, even as we also long to see you;', pt: 'Mas agora que Timóteo acaba de regressar do vosso meio, trazendo-nos boas notícias da vossa fé e do vosso amor, dizendo que sempre nos tendes em afetuosa lembrança, anelando ver-nos assim como nós também a vós;' },
      { v: 7, en: 'for this cause, brothers, we were comforted over you in all our distress and affliction through your faith.', pt: 'por isso, irmãos, em toda a nossa necessidade e tribulação, ficamos consolados acerca de vós, pela vossa fé,' },
      { v: 8, en: 'For now we live, if you stand fast in the Lord.', pt: 'porque agora vivemos, se estais firmes no Senhor.' },
      { v: 9, en: 'For what thanksgiving can we render again to God for you, for all the joy with which we rejoice for your sakes before our God;', pt: 'Pois, que ação de graças podemos render a Deus por vós, por todo o gozo com que nos regozijamos por vossa causa diante do nosso Deus,' },
      { v: 10, en: 'night and day praying exceedingly that we may see your face, and may perfect that which is lacking in your faith?', pt: 'rogando incessantemente, de noite e de dia, para que possamos ver o vosso rosto e suprir o que falta à vossa fé?' },
      { v: 11, en: 'Now may our God and Father himself, and our Lord Jesus Christ, direct our way to you;', pt: 'Ora, o próprio Deus e Pai nosso e o nosso Senhor Jesus nos abram o caminho até vós,' },
      { v: 12, en: 'and the Lord make you to increase and abound in love one toward another, and toward all men, even as we also do toward you,', pt: 'e o Senhor vos faça crescer e abundar em amor uns para com os outros e para com todos, como também nós abundamos para convosco;' },
      { v: 13, en: 'to the end he may establish your hearts blameless in holiness before our God and Father, at the coming of our Lord Jesus with all his saints.', pt: 'para vos confirmar os corações, de sorte que sejam irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso Senhor Jesus com todos os seus santos.' },
    ],
    4: [
      { v: 1, en: 'Finally then, brothers, we beg and exhort you in the Lord Jesus, that as you received from us how you ought to walk and to please God, that you abound more and more.', pt: 'Finalmente, irmãos, vos rogamos e exortamos no Senhor Jesus que, como aprendestes de nós de que maneira deveis andar e agradar a Deus, assim como estais fazendo, nisso mesmo abundeis cada vez mais.' },
      { v: 2, en: 'For you know what instructions we gave you through the Lord Jesus.', pt: 'Pois vós sabeis que preceitos vos temos dado pelo Senhor Jesus.' },
      { v: 3, en: 'For this is the will of God: your sanctification, that you abstain from sexual immorality,', pt: 'Porque esta é a vontade de Deus, a saber, a vossa santificação: que vos abstenhais da prostituição,' },
      { v: 4, en: 'that each one of you know how to control his own body in sanctification and honor,', pt: 'que cada um de vós saiba possuir o seu vaso em santidade e honra,' },
      { v: 5, en: 'not in the passion of lust, even as the Gentiles who don’t know God;', pt: 'não na paixão da concupiscência, como os gentios que não conhecem a Deus;' },
      { v: 6, en: 'that no one should take advantage of and wrong a brother or sister in this matter; because the Lord is an avenger in all these things, as also we forewarned you and testified.', pt: 'ninguém iluda ou defraude nisso a seu irmão, porque o Senhor é vingador de todas estas coisas, como também antes vo-lo dissemos e testificamos.' },
      { v: 7, en: 'For God called us not for uncleanness, but in sanctification.', pt: 'Porque Deus não nos chamou para a imundícia, mas para a santificação.' },
      { v: 8, en: 'Therefore he who rejects this doesn’t reject man, but God, who has also given his Holy Spirit to you.', pt: 'Portanto, quem rejeita isso não rejeita ao homem, mas sim a Deus, que vos dá o seu Espírito Santo.' },
      { v: 9, en: 'But concerning brotherly love, you have no need that one write to you. For you yourselves are taught by God to love one another,', pt: 'Quanto, porém, ao amor fraternal, não necessitais de que se vos escreva, visto que vós mesmos sois instruídos por Deus a vos amardes uns aos outros;' },
      { v: 10, en: 'for indeed you do it toward all the brothers who are in all Macedonia. But we exhort you, brothers, that you abound more and more;', pt: 'porque certamente já o fazeis para com todos os irmãos que estão por toda a Macedônia. Exortamo-vos, porém, irmãos, a que ainda nisto abundeis cada vez mais,' },
      { v: 11, en: 'and that you make it your ambition to lead a quiet life, and to do your own business, and to work with your own hands, even as we instructed you;', pt: 'e procureis viver quietos, tratar dos vossos próprios negócios, e trabalhar com vossas próprias mãos, como já vo-lo mandamos,' },
      { v: 12, en: 'that you may walk properly toward those who are outside, and may have need of nothing.', pt: 'a fim de que andeis dignamente para com os que estão de fora, e não tenhais necessidade de coisa alguma.' },
      { v: 13, en: 'But we don’t want you to be ignorant, brothers, concerning those who have fallen asleep, so that you don’t grieve like the rest, who have no hope.', pt: 'Não queremos, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais como os outros que não têm esperança.' },
      { v: 14, en: 'For if we believe that Jesus died and rose again, even so God will bring with him those who have fallen asleep in Jesus.', pt: 'Porque, se cremos que Jesus morreu e ressurgiu, assim também aos que dormem, Deus, mediante Jesus, os tornará a trazer juntamente com ele.' },
      { v: 15, en: 'For this we tell you by the word of the Lord, that we who are alive, who are left until the coming of the Lord, will in no way precede those who have fallen asleep.', pt: 'Dizemo-vos, pois, isto pela palavra do Senhor: que nós, os que ficarmos vivos para a vinda do Senhor, de modo algum precederemos os que já dormem.' },
      { v: 16, en: 'For the Lord himself will descend from heaven with a shout, with the voice of the archangel, and with God’s trumpet. The dead in Christ will rise first,', pt: 'Porque o Senhor mesmo descerá do céu com grande brado, à voz do arcanjo, ao som da trombeta de Deus, e os que morreram em Cristo ressuscitarão primeiro.' },
      { v: 17, en: 'then we who are alive, who are left, will be caught up together with them in the clouds, to meet the Lord in the air. So we will be with the Lord forever.', pt: 'Depois nós, os que ficarmos vivos seremos arrebatados juntamente com eles, nas nuvens, ao encontro do Senhor nos ares, e assim estaremos para sempre com o Senhor.' },
      { v: 18, en: 'Therefore comfort one another with these words.', pt: 'Portanto, consolai-vos uns aos outros com estas palavras.' },
    ],
    5: [
      { v: 1, en: 'But concerning the times and the seasons, brothers, you have no need that anything be written to you.', pt: 'Mas, irmãos, acerca dos tempos e das épocas não necessitais de que se vos escreva:' },
      { v: 2, en: 'For you yourselves know well that the day of the Lord comes like a thief in the night.', pt: 'porque vós mesmos sabeis perfeitamente que o dia do Senhor virá como vem o ladrão de noite;' },
      { v: 3, en: 'For when they are saying, “Peace and safety,” then sudden destruction will come on them, like birth pains on a pregnant woman; and they will in no way escape.', pt: 'pois quando estiverem dizendo: Paz e segurança! então lhes sobrevirá repentina destruição, como as dores de parto àquela que está grávida; e de modo nenhum escaparão.' },
      { v: 4, en: 'But you, brothers, aren’t in darkness, that the day should overtake you like a thief.', pt: 'Mas vós, irmãos, não estais em trevas, para que aquele dia, como ladrão, vos surpreenda;' },
      { v: 5, en: 'You are all children of light, and children of the day. We don’t belong to the night, nor to darkness,', pt: 'porque todos vós sois filhos da luz e filhos do dia; nós não somos da noite nem das trevas;' },
      { v: 6, en: 'so then let’s not sleep, as the rest do, but let’s watch and be sober.', pt: 'não durmamos, pois, como os demais, antes vigiemos e sejamos sóbrios.' },
      { v: 7, en: 'For those who sleep, sleep in the night; and those who are drunk are drunk in the night.', pt: 'Porque os que dormem, dormem de noite, e os que se embriagam, embriagam-se de noite;' },
      { v: 8, en: 'But let us, since we belong to the day, be sober, putting on the breastplate of faith and love, and, for a helmet, the hope of salvation.', pt: 'mas nós, porque somos do dia, sejamos sóbrios, vestindo-nos da couraça da fé e do amor, e tendo por capacete a esperança da salvação;' },
      { v: 9, en: 'For God didn’t appoint us to wrath, but to the obtaining of salvation through our Lord Jesus Christ,', pt: 'porque Deus não nos destinou para a ira, mas para alcançarmos a salvação por nosso Senhor Jesus Cristo,' },
      { v: 10, en: 'who died for us, that, whether we wake or sleep, we should live together with him.', pt: 'que morreu por nós, para que, quer vigiemos, quer durmamos, vivamos juntamente com ele.' },
      { v: 11, en: 'Therefore exhort one another, and build each other up, even as you also do.', pt: 'Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como na verdade o estais fazendo.' },
      { v: 12, en: 'But we beg you, brothers, to know those who labor among you, and are over you in the Lord, and admonish you,', pt: 'Ora, rogamo-vos, irmãos, que reconheçais os que trabalham entre vós, presidem sobre vós no Senhor e vos admoestam;' },
      { v: 13, en: 'and to respect and honor them in love for their work’s sake. Be at peace among yourselves.', pt: 'e que os tenhais em grande estima e amor, por causa da sua obras. Tende paz entre vós.' },
      { v: 14, en: 'We exhort you, brothers, admonish the disorderly, encourage the faint-hearted, support the weak, be patient toward all.', pt: 'Exortamo-vos também, irmãos, a que admoesteis os insubordinados, consoleis os desanimados, ampareis os fracos e sejais longânimos para com todos.' },
      { v: 15, en: 'See that no one returns evil for evil to anyone, but always follow after that which is good, for one another, and for all.', pt: 'Vede que ninguém dê a outrem mal por mal, mas segui sempre o bem, uns para com os outros, e para com todos.' },
      { v: 16, en: 'Rejoice always.', pt: 'Regozijai-vos sempre.' },
      { v: 17, en: 'Pray without ceasing.', pt: 'Orai sem cessar.' },
      { v: 18, en: 'In everything give thanks, for this is the will of God in Christ Jesus toward you.', pt: 'Em tudo dai graças; porque esta é a vontade de Deus em Cristo Jesus para convosco.' },
      { v: 19, en: 'Don’t quench the Spirit.', pt: 'Não extingais o Espírito;' },
      { v: 20, en: 'Don’t despise prophesies.', pt: 'não desprezeis as profecias,' },
      { v: 21, en: 'Test all things, and hold firmly that which is good.', pt: 'mas ponde tudo à prova. Retende o que é bom;' },
      { v: 22, en: 'Abstain from every form of evil.', pt: 'Abstende-vos de toda espécie de mal.' },
      { v: 23, en: 'May the God of peace himself sanctify you completely. May your whole spirit, soul, and body be preserved blameless at the coming of our Lord Jesus Christ.', pt: 'E o próprio Deus de paz vos santifique completamente; e o vosso espírito, e alma e corpo sejam plenamente conservados irrepreensíveis para a vinda de nosso Senhor Jesus Cristo.' },
      { v: 24, en: 'He who calls you is faithful, who will also do it.', pt: 'Fiel é o que vos chama, e ele também o fará.' },
      { v: 25, en: 'Brothers, pray for us.', pt: 'Irmãos, orai por nós.' },
      { v: 26, en: 'Greet all the brothers with a holy kiss.', pt: 'Saudai a todos os irmãos com ósculo santo.' },
      { v: 27, en: 'I solemnly command you by the Lord that this letter be read to all the holy brothers.', pt: 'Pelo Senhor vos conjuro que esta epístola seja lida a todos os irmãos.' },
      { v: 28, en: 'The grace of our Lord Jesus Christ be with you. Amen.', pt: 'A graça de nosso Senhor Jesus Cristo seja convosco.' },
    ],
  },
};

export default book;
