import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: '2timothy',
  name: '2 Timóteo',
  englishName: '2 Timothy',
  testament: 'new',
  chapters: {
    1: [
      { v: 1, en: 'Paul, an apostle of Jesus Christ through the will of God, according to the promise of the life which is in Christ Jesus,', pt: 'Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,' },
      { v: 2, en: 'to Timothy, my beloved child: Grace, mercy, and peace, from God the Father and Christ Jesus our Lord.', pt: 'a Timóteo, amado filho: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus nosso Senhor.' },
      { v: 3, en: 'I thank God, whom I serve as my forefathers did, with a pure conscience. How unceasing is my memory of you in my petitions, night and day', pt: 'Dou graças a Deus, a quem desde os meus antepassados sirvo com uma consciência pura, de que sem cessar faço menção de ti em minhas súplicas de noite e de dia;' },
      { v: 4, en: 'longing to see you, remembering your tears, that I may be filled with joy;', pt: 'e, recordando-me das tuas lágrimas, desejo muito ver-te, para me encher de gozo;' },
      { v: 5, en: 'having been reminded of the sincere faith that is in you; which lived first in your grandmother Lois, and your mother Eunice, and, I am persuaded, in you also.', pt: 'trazendo à memória a fé não fingida que há em ti, a qual habitou primeiro em tua avó Loide, e em tua mãe Eunice e estou certo de que também habita em ti.' },
      { v: 6, en: 'For this cause, I remind you that you should stir up the gift of God which is in you through the laying on of my hands.', pt: 'Por esta razão te lembro que despertes o dom de Deus, que há em ti pela imposição das minhas mãos.' },
      { v: 7, en: 'For God didn’t give us a spirit of fear, but of power, love, and self-control.', pt: 'Porque Deus não nos deu o espírito de covardia, mas de poder, de amor e de moderação.' },
      { v: 8, en: 'Therefore don’t be ashamed of the testimony of our Lord, nor of me his prisoner; but endure hardship for the Good News according to the power of God,', pt: 'Portanto não te envergonhes do testemunho de nosso Senhor, nem de mim, que sou prisioneiro seu; antes participa comigo dos sofrimentos do evangelho segundo o poder de Deus,' },
      { v: 9, en: 'who saved us and called us with a holy calling, not according to our works, but according to his own purpose and grace, which was given to us in Christ Jesus before times eternal,', pt: 'que nos salvou, e chamou com uma santa vocação, não segundo as nossas obras, mas segundo o seu próprio propósito e a graça que nos foi dada em Cristo Jesus antes dos tempos eternos,' },
      { v: 10, en: 'but has now been revealed by the appearing of our Savior, Christ Jesus, who abolished death, and brought life and immortality to light through the Good News.', pt: 'e que agora se manifestou pelo aparecimento de nosso Salvador Cristo Jesus, o qual destruiu a morte, e trouxe à luz a vida e a imortalidade pelo evangelho,' },
      { v: 11, en: 'For this, I was appointed as a preacher, an apostle, and a teacher of the Gentiles.', pt: 'do qual fui constituído pregador, apóstolo e mestre.' },
      { v: 12, en: 'For this cause I also suffer these things. Yet I am not ashamed, for I know him whom I have believed, and I am persuaded that he is able to guard that which I have committed to him against that day.', pt: 'Por esta razão sofro também estas coisas, mas não me envergonho; porque eu sei em quem tenho crido, e estou certo de que ele é poderoso para guardar o meu depósito até aquele dia.' },
      { v: 13, en: 'Hold the pattern of sound words which you have heard from me, in faith and love which is in Christ Jesus.', pt: 'Conserva o modelo das sãs palavras que de mim tens ouvido na fé e no amor que há em Cristo Jesus;' },
      { v: 14, en: 'That good thing which was committed to you, guard through the Holy Spirit who dwells in us.', pt: 'guarda o bom depósito com o auxílio do Espírito Santo, que habita em nós.' },
      { v: 15, en: 'This you know, that all who are in Asia turned away from me; of whom are Phygelus and Hermogenes.', pt: 'Bem sabes isto, que me abandonaram todos os que estão na Ásia, entre eles Fígelo e Hermógenes.' },
      { v: 16, en: 'May the Lord grant mercy to the house of Onesiphorus, for he often refreshed me, and was not ashamed of my chain,', pt: 'O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes ele me recreou, e não se envergonhou das minhas cadeias;' },
      { v: 17, en: 'but when he was in Rome, he sought me diligently, and found me', pt: 'antes quando veio a Roma, diligentemente me procurou e me achou.' },
      { v: 18, en: '(the Lord grant to him to find the Lord’s mercy in that day); and in how many things he served at Ephesus, you know very well.', pt: 'O Senhor lhe conceda que naquele dia ache misericórdia diante do Senhor. E quantos serviços prestou em Éfeso melhor o sabes tu.' },
    ],
    2: [
      { v: 1, en: 'You therefore, my child, be strengthened in the grace that is in Christ Jesus.', pt: 'Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus;' },
      { v: 2, en: 'The things which you have heard from me among many witnesses, commit the same to faithful men, who will be able to teach others also.', pt: 'e o que de mim ouviste de muitas testemunhas, transmite-o a homens fiéis, que sejam idôneos para também ensinarem os outros.' },
      { v: 3, en: 'You therefore must endure hardship, as a good soldier of Christ Jesus.', pt: 'Sofre comigo como bom soldado de Cristo Jesus.' },
      { v: 4, en: 'No soldier on duty entangles himself in the affairs of life, that he may please him who enrolled him as a soldier.', pt: 'Nenhum soldado em serviço se embaraça com negócios desta vida, a fim de agradar àquele que o alistou para a guerra.' },
      { v: 5, en: 'Also, if anyone competes in athletics, he isn’t crowned unless he has competed by the rules.', pt: 'E também se um atleta lutar nos jogos públicos, não será coroado se não lutar legitimamente.' },
      { v: 6, en: 'The farmer who labors must be the first to get a share of the crops.', pt: 'O lavrador que trabalha deve ser o primeiro a gozar dos frutos.' },
      { v: 7, en: 'Consider what I say, and may the Lord give you understanding in all things.', pt: 'Considera o que digo, porque o Senhor te dará entendimento em tudo.' },
      { v: 8, en: 'Remember Jesus Christ, risen from the dead, of the offspring of David, according to my Good News,', pt: 'Lembra-te de Jesus Cristo, ressurgido dentre os mortos, descendente de Davi, segundo o meu evangelho,' },
      { v: 9, en: 'in which I suffer hardship to the point of chains as a criminal. But God’s word isn’t chained.', pt: 'pelo qual sofro a ponto de ser preso como malfeitor; mas a palavra de Deus não está presa.' },
      { v: 10, en: 'Therefore I endure all things for the chosen ones’ sake, that they also may obtain the salvation which is in Christ Jesus with eternal glory.', pt: 'Por isso, tudo suporto por amor dos eleitos, para que também eles alcancem a salvação que há em Cristo Jesus com glória eterna.' },
      { v: 11, en: 'This saying is trustworthy: “For if we died with him, we will also live with him.', pt: 'Fiel é esta palavra: Se, pois, já morremos com ele, também com ele viveremos;' },
      { v: 12, en: 'If we endure, we will also reign with him. If we deny him, he also will deny us.', pt: 'se perseveramos, com ele também reinaremos; se o negarmos, também ele nos negará;' },
      { v: 13, en: 'If we are faithless, he remains faithful. For he can’t deny himself.”', pt: 'se somos infiéis, ele permanece fiel; porque não pode negar-se a si mesmo.' },
      { v: 14, en: 'Remind them of these things, charging them in the sight of the Lord, that they don’t argue about words, to no profit, to the subverting of those who hear.', pt: 'Lembra-lhes estas coisas, conjurando-os diante de Deus que não tenham contendas de palavras, que para nada aproveitam, senão para subverter os ouvintes.' },
      { v: 15, en: 'Give diligence to present yourself approved by God, a workman who doesn’t need to be ashamed, properly handling the Word of Truth.', pt: 'Procura apresentar-te diante de Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.' },
      { v: 16, en: 'But shun empty chatter, for it will go further in ungodliness,', pt: 'Mas evita as conversas vãs e profanas; porque os que delas usam passarão a impiedade ainda maior,' },
      { v: 17, en: 'and those words will consume like gangrene, of whom is Hymenaeus and Philetus;', pt: 'e as suas palavras alastrarão como gangrena; entre os quais estão Himeneu e Fileto,' },
      { v: 18, en: 'men who have erred concerning the truth, saying that the resurrection is already past, and overthrowing the faith of some.', pt: 'que se desviaram da verdade, dizendo que a ressurreição é já passada, e assim pervertem a fé a alguns.' },
      { v: 19, en: 'However God’s firm foundation stands, having this seal, “The Lord knows those who are his,” and, “Let every one who names the name of the Lord depart from unrighteousness.”', pt: 'Todavia o firme fundamento de Deus permanece, tendo este selo: O Senhor conhece os seus, e: Aparte-se da injustiça todo aquele que profere o nome do Senhor.' },
      { v: 20, en: 'Now in a large house there are not only vessels of gold and of silver, but also of wood and of clay. Some are for honor, and some for dishonor.', pt: 'Ora, numa grande casa, não somente há vasos de ouro e de prata, mas também de madeira e de barro; e uns, na verdade, para uso honroso, outros, porém, para uso desonroso.' },
      { v: 21, en: 'If anyone therefore purges himself from these, he will be a vessel for honor, sanctified, and suitable for the master’s use, prepared for every good work.', pt: 'Se, pois, alguém se purificar destas coisas, será vaso para honra, santificado e útil ao Senhor, preparado para toda boa obra.' },
      { v: 22, en: 'Flee from youthful lusts; but pursue righteousness, faith, love, and peace with those who call on the Lord out of a pure heart.', pt: 'Foge também das paixões da mocidade, e segue a justiça, a fé, o amor, a paz com os que, de coração puro, invocam o Senhor.' },
      { v: 23, en: 'But refuse foolish and ignorant questionings, knowing that they generate strife.', pt: 'E rejeita as questões tolas e desassisadas, sabendo que geram contendas;' },
      { v: 24, en: 'The Lord’s servant must not quarrel, but be gentle towards all, able to teach, patient,', pt: 'e ao servo do Senhor não convém contender, mas sim ser brando para com todos, apto para ensinar, paciente;' },
      { v: 25, en: 'in gentleness correcting those who oppose him: perhaps God may give them repentance leading to a full knowledge of the truth,', pt: 'corrigindo com mansidão os que resistem, na esperança de que Deus lhes conceda o arrependimento para conhecerem plenamente a verdade,' },
      { v: 26, en: 'and they may recover themselves out of the devil’s snare, having been taken captive by him to his will.', pt: 'e que se desprendam dos laços do Diabo (por quem haviam sido presos), para cumprirem a vontade de Deus.' },
    ],
    3: [
      { v: 1, en: 'But know this, that in the last days, grievous times will come.', pt: 'Sabe, porém, isto, que nos últimos dias sobrevirão tempos penosos;' },
      { v: 2, en: 'For men will be lovers of self, lovers of money, boastful, arrogant, blasphemers, disobedient to parents, unthankful, unholy,', pt: 'pois os homens serão amantes de si mesmos, gananciosos, presunçosos, soberbos, blasfemos, desobedientes a seus pais, ingratos, ímpios,' },
      { v: 3, en: 'without natural affection, unforgiving, slanderers, without self-control, fierce, not lovers of good,', pt: 'sem afeição natural, implacáveis, caluniadores, incontinentes, cruéis, inimigos do bem,' },
      { v: 4, en: 'traitors, headstrong, conceited, lovers of pleasure rather than lovers of God;', pt: 'traidores, atrevidos, orgulhosos, mais amigos dos deleites do que amigos de Deus,' },
      { v: 5, en: 'holding a form of godliness, but having denied its power. Turn away from these, also.', pt: 'tendo aparência de piedade, mas negando-lhe o poder. Afasta- te também desses.' },
      { v: 6, en: 'For some of these are people who creep into houses, and take captive gullible women loaded down with sins, led away by various lusts,', pt: 'Porque deste número são os que se introduzem pelas casas, e levam cativas mulheres néscias carregadas de pecados, levadas de várias concupiscências;' },
      { v: 7, en: 'always learning, and never able to come to the knowledge of the truth.', pt: 'sempre aprendendo, mas nunca podendo chegar ao pleno conhecimento da verdade.' },
      { v: 8, en: 'Even as Jannes and Jambres opposed Moses, so do these also oppose the truth; men corrupted in mind, who concerning the faith are rejected.', pt: 'E assim como Janes e Jambres resistiram a Moisés, assim também estes resistem à verdade, sendo homens corruptos de entendimento e réprobos quanto à fé.' },
      { v: 9, en: 'But they will proceed no further. For their folly will be evident to all men, as theirs also came to be.', pt: 'Não irão, porém, avante; porque a todos será manifesta a sua insensatez, como também o foi a daqueles.' },
      { v: 10, en: 'But you did follow my teaching, conduct, purpose, faith, patience, love, steadfastness,', pt: 'Tu, porém, tens observado a minha doutrina, procedimento, intenção, fé, longanimidade, amor, perseverança,' },
      { v: 11, en: 'persecutions, and sufferings: those things that happened to me at Antioch, Iconium, and Lystra. I endured those persecutions. The Lord delivered me out of them all.', pt: 'as minhas perseguições e aflições, quais as que sofri em Antioquia, em Icônio, em Listra; quantas perseguições suportei! e de todas o Senhor me livrou.' },
      { v: 12, en: 'Yes, and all who desire to live godly in Christ Jesus will suffer persecution.', pt: 'E na verdade todos os que querem viver piamente em Cristo Jesus padecerão perseguições.' },
      { v: 13, en: 'But evil men and impostors will grow worse and worse, deceiving and being deceived.', pt: 'Mas os homens maus e impostores irão de mal a pior, enganando e sendo enganados.' },
      { v: 14, en: 'But you remain in the things which you have learned and have been assured of, knowing from whom you have learned them.', pt: 'Tu, porém, permanece naquilo que aprendeste, e de que foste inteirado, sabendo de quem o tens aprendido,' },
      { v: 15, en: 'From infancy, you have known the holy Scriptures which are able to make you wise for salvation through faith, which is in Christ Jesus.', pt: 'e que desde a infância sabes as sagradas letras, que podem fazer-te sábio para a salvação, pela que há em Cristo Jesus.' },
      { v: 16, en: 'Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness,', pt: 'Toda Escritura é divinamente inspirada e proveitosa para ensinar, para repreender, para corrigir, para instruir em justiça;' },
      { v: 17, en: 'that the man of God may be complete, thoroughly equipped for every good work.', pt: 'para que o homem de Deus seja perfeito, e perfeitamente preparado para toda boa obra.' },
    ],
    4: [
      { v: 1, en: 'I command you therefore before God and the Lord Jesus Christ, who will judge the living and the dead at his appearing and his Kingdom:', pt: 'Conjuro-te diante de Deus e de Cristo Jesus, que há de julgar os vivos e os mortos, pela sua vinda e pelo seu reino;' },
      { v: 2, en: 'preach the word; be urgent in season and out of season; reprove, rebuke, and exhort, with all patience and teaching.', pt: 'prega a palavra, insta a tempo e fora de tempo, admoesta, repreende, exorta, com toda longanimidade e ensino.' },
      { v: 3, en: 'For the time will come when they will not listen to the sound doctrine, but, having itching ears, will heap up for themselves teachers after their own lusts;', pt: 'Porque virá tempo em que não suportarão a sã doutrina; mas, tendo grande desejo de ouvir coisas agradáveis, ajuntarão para si mestres segundo os seus próprios desejos,' },
      { v: 4, en: 'and will turn away their ears from the truth, and turn away to fables.', pt: 'e não só desviarão os ouvidos da verdade, mas se voltarão às fábulas.' },
      { v: 5, en: 'But you be sober in all things, suffer hardship, do the work of an evangelist, and fulfill your ministry.', pt: 'Tu, porém, sê sóbrio em tudo, sofre as aflições, faze a obra de um evangelista, cumpre o teu ministério.' },
      { v: 6, en: 'For I am already being offered, and the time of my departure has come.', pt: 'Quanto a mim, já estou sendo derramado como libação, e o tempo da minha partida está próximo.' },
      { v: 7, en: 'I have fought the good fight. I have finished the course. I have kept the faith.', pt: 'Combati o bom combate, acabei a carreira, guardei a fé.' },
      { v: 8, en: 'From now on, there is stored up for me the crown of righteousness, which the Lord, the righteous judge, will give to me on that day; and not to me only, but also to all those who have loved his appearing.', pt: 'Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amarem a sua vinda.' },
      { v: 9, en: 'Be diligent to come to me soon,', pt: 'Procura vir ter comigo breve;' },
      { v: 10, en: 'for Demas left me, having loved this present world, and went to Thessalonica; Crescens to Galatia, and Titus to Dalmatia.', pt: 'pois Demas me abandonou, tendo amado o mundo presente, e foi para Tessalônica, Crescente para a Galácia, Tito para a Dalmácia;' },
      { v: 11, en: 'Only Luke is with me. Take Mark, and bring him with you, for he is useful to me for service.', pt: 'só Lucas está comigo. Toma a Marcos e traze-o contigo, porque me é muito útil para o ministério.' },
      { v: 12, en: 'But I sent Tychicus to Ephesus.', pt: 'Quanto a Tíquico, enviei-o a Éfeso.' },
      { v: 13, en: 'Bring the cloak that I left at Troas with Carpus when you come, and the books, especially the parchments.', pt: 'Quando vieres traze a capa que deixei em Trôade, em casa de Carpo, e os livros, especialmente os pergaminhos.' },
      { v: 14, en: 'Alexander, the coppersmith, did much evil to me. The Lord will repay him according to his deeds,', pt: 'Alexandre, o latoeiro, me fez muito mal; o Senhor lhe retribuirá segundo as suas obras.' },
      { v: 15, en: 'of whom you also must beware; for he greatly opposed our words.', pt: 'Tu também guarda-te dele; porque resistiu muito às nossas palavras.' },
      { v: 16, en: 'At my first defense, no one came to help me, but all left me. May it not be held against them.', pt: 'Na minha primeira defesa ninguém me assistiu, antes todos me desampararam. Que isto não lhes seja imputado.' },
      { v: 17, en: 'But the Lord stood by me, and strengthened me, that through me the message might be fully proclaimed, and that all the Gentiles might hear; and I was delivered out of the mouth of the lion.', pt: 'Mas o Senhor esteve ao meu lado e me fortaleceu, para que por mim fosse cumprida a pregação, e a ouvissem todos os gentios; e fiquei livre da boca do leão,' },
      { v: 18, en: 'And the Lord will deliver me from every evil work, and will preserve me for his heavenly Kingdom; to whom be the glory forever and ever. Amen.', pt: 'E o Senhor me livrará de toda má obra, e me levará salvo para o seu reino celestial; a quem seja glória para todo o sempre. Amém.' },
      { v: 19, en: 'Greet Prisca and Aquila, and the house of Onesiphorus.', pt: 'Saúda a Prisca e a áquila e à casa de Onesíforo.' },
      { v: 20, en: 'Erastus remained at Corinth, but I left Trophimus at Miletus sick.', pt: 'Erasto ficou em Corinto; a Trófimo deixei doente em Mileto.' },
      { v: 21, en: 'Be diligent to come before winter. Eubulus salutes you, as do Pudens, Linus, Claudia, and all the brothers.', pt: 'Apressa-te a vir antes do inverno. Saúdam-te åubulo, Pudente, Lino, Cláudia, e todos os irmãos.' },
      { v: 22, en: 'The Lord Jesus Christ be with your spirit. Grace be with you. Amen.', pt: 'O Senhor seja com o teu espírito. A graça seja convosco.' },
    ],
  },
};

export default book;
