import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: 'haggai',
  name: 'Ageu',
  englishName: 'Haggai',
  testament: 'old',
  chapters: {
    1: [
      { v: 1, en: 'In the second year of Darius the king, in the sixth month, in the first day of the month, Yahweh’s word came by Haggai, the prophet, to Zerubbabel, the son of Shealtiel, governor of Judah, and to Joshua, the son of Jehozadak, the high priest, saying,', pt: 'No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do Senhor, por intermédio do profeta Ageu, a Zorobabel, governador de Judá, filho de Sealtiel, e a Josué, o sumo sacerdote, filho de Jeozadaque, dizendo:' },
      { v: 2, en: '“This is what Yahweh of Armies says: These people say, ‘The time hasn’t yet come, the time for Yahweh’s house to be built.’”', pt: 'Assim fala o Senhor dos exércitos, dizendo: Este povo diz: Não veio ainda o tempo, o tempo de se edificar a casa do Senhor.' },
      { v: 3, en: 'Then Yahweh’s word came by Haggai, the prophet, saying,', pt: 'Veio, pois, a palavra do Senhor, por intermédio do profeta Ageu, dizendo:' },
      { v: 4, en: '“Is it a time for you yourselves to dwell in your paneled houses, while this house lies waste?', pt: 'Acaso é tempo de habitardes nas vossas casas forradas, enquanto esta casa fica desolada?' },
      { v: 5, en: 'Now therefore this is what Yahweh of Armies says: Consider your ways.', pt: 'Ora pois, assim diz o Senhor dos exércitos: Considerai os vossos caminhos.' },
      { v: 6, en: 'You have sown much, and bring in little. You eat, but you don’t have enough. You drink, but you aren’t filled with drink. You clothe yourselves, but no one is warm, and he who earns wages earns wages to put them into a bag with holes in it.”', pt: 'Tendes semeado muito, e recolhido pouco; comeis, mas não vos fartais; bebeis, mas não vos saciais; vestis-vos, mas ninguém se aquece; e o que recebe salário, recebe-o para o meter num saco furado.' },
      { v: 7, en: 'This is what Yahweh of Armies says: “Consider your ways.', pt: 'Assim diz o Senhor dos exércitos: Considerai os vossos caminhos.' },
      { v: 8, en: 'Go up to the mountain, bring wood, and build the house. I will take pleasure in it, and I will be glorified,” says Yahweh.', pt: 'Subi ao monte, e trazei madeira, e edificai a casa; e dela me deleitarei, e serei glorificado, diz o Senhor.' },
      { v: 9, en: '“You looked for much, and, behold, it came to little; and when you brought it home, I blew it away. Why?” says Yahweh of Armies, “Because of my house that lies waste, while each of you is busy with his own house.', pt: 'Esperastes o muito, mas eis que veio a ser pouco; e esse pouco, quando o trouxestes para casa, eu o dissipei com um assopro. Por que causa? diz o Senhor dos exércitos. Por causa da minha casa, que está em ruínas, enquanto correis, cada um de vós, à sua propria casa.' },
      { v: 10, en: 'Therefore for your sake the heavens withhold the dew, and the earth withholds its fruit.', pt: 'Por isso os ceus por cima de vós retêm o orvalho, e a terra retém os seus frutos.' },
      { v: 11, en: 'I called for a drought on the land, on the mountains, on the grain, on the new wine, on the oil, on that which the ground produces, on men, on livestock, and on all the labor of the hands.”', pt: 'E mandei vir a seca sobre a terra, e sobre as colinas, sobre o trigo e o mosto e o azeite, e sobre tudo o que a terra produz; como também sobre os homens e os animais, e sobre todo o seu trabalho.' },
      { v: 12, en: 'Then Zerubbabel, the son of Shealtiel, and Joshua, the son of Jehozadak, the high priest, with all the remnant of the people, obeyed Yahweh, their God’s voice, and the words of Haggai, the prophet, as Yahweh, their God, had sent him; and the people feared Yahweh.', pt: 'Então Zorobabel, filho de Sealtiel, e o sumo sacerdote Josué, filho de Jeozadaque, juntamente com todo o resto do povo, obedeceram a voz do Senhor seu Deus, e as palavras do profeta Ageu, como o Senhor seu Deus o tinha enviado; e temeu o povo diante do Senhor.' },
      { v: 13, en: 'Then Haggai, Yahweh’s messenger, spoke Yahweh’s message to the people, saying, “I am with you,” says Yahweh.', pt: 'Então Ageu, o mensageiro do Senhor, falou ao povo, conforme a mensagem do Senhor, dizendo: Eu sou convosco, e diz o Senhor.' },
      { v: 14, en: 'Yahweh stirred up the spirit of Zerubbabel, the son of Shealtiel, governor of Judah, and the spirit of Joshua, the son of Jehozadak, the high priest, and the spirit of all the remnant of the people; and they came and worked on the house of Yahweh of Armies, their God,', pt: 'E o Senhor suscitou o espírito do governador de Judá Zorobabel, filho de Sealtiel, e o espírito do sumo sacerdote Josué, filho de Jeozadaque, e o espírito de todo o resto do povo; e eles vieram, e começaram a trabalhar na casa do Senhor dos exércitos, seu Deus,' },
      { v: 15, en: 'in the twenty-fourth day of the month, in the sixth month, in the second year of Darius the king.', pt: 'ao vigésimo quarto dia do sexto mês.' },
    ],
    2: [
      { v: 1, en: 'In the seventh month, in the twenty-first day of the month, Yahweh’s word came by Haggai the prophet, saying,', pt: 'No segundo ano do rei Dario, no sétimo mês, ao vigésimo primeiro do mês, veio a palavra do Senhor por intermédio do profeta Ageu, dizendo:' },
      { v: 2, en: '“Speak now to Zerubbabel, the son of Shealtiel, governor of Judah, and to Joshua, the son of Jehozadak, the high priest, and to the remnant of the people, saying,', pt: 'Fala agora ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque, e ao resto do povo, dizendo:' },
      { v: 3, en: '‘Who is left among you who saw this house in its former glory? How do you see it now? Isn’t it in your eyes as nothing?', pt: 'Quem há entre vós, dos sobreviventes, que viu esta casa na sua primeira glória? Em que estado a vedes agora? Não é como nada em vossos olhos?' },
      { v: 4, en: 'Yet now be strong, Zerubbabel,’ says Yahweh. ‘Be strong, Joshua, son of Jehozadak, the high priest. Be strong, all you people of the land,’ says Yahweh, ‘and work, for I am with you,’ says Yahweh of Armies.', pt: 'Ora, pois, esforça-te, Zorobabel, diz o Senhor, e esforça-te, sumo sacerdote Josué, filho de Jeozadaque, e esforçai-vos, todo o povo da terra, diz o Senhor, e trabalhai; porque eu sou convosco, diz o Senhor dos exércitos,' },
      { v: 5, en: 'This is the word that I covenanted with you when you came out of Egypt, and my Spirit lived among you. ‘Don’t be afraid.’', pt: 'segundo o pacto que fiz convosco, quando saístes do Egito, e o meu Espírito habita no meio de vós; não temais.' },
      { v: 6, en: 'For this is what Yahweh of Armies says: ‘Yet once, it is a little while, and I will shake the heavens, the earth, the sea, and the dry land;', pt: 'Pois assim diz o Senhor dos exércitos; Ainda uma vez, daqui a pouco, e abalarei os céus e a terra, o mar e a terra seca.' },
      { v: 7, en: 'and I will shake all nations. The precious things of all nations will come, and I will fill this house with glory, says Yahweh of Armies.', pt: 'Abalarei todas as nações; e as coisas preciosas de todas as nações virão, e encherei de glória esta casa, diz o Senhor dos exércitos.' },
      { v: 8, en: 'The silver is mine, and the gold is mine,’ says Yahweh of Armies.', pt: 'Minha é a prata, e meu é o ouro, diz o Senhor dos exércitos.' },
      { v: 9, en: '‘The latter glory of this house will be greater than the former,’ says Yahweh of Armies; ‘and in this place will I give peace,’ says Yahweh of Armies.”', pt: 'A glória desta última casa será maior do que a da primeira, diz o Senhor dos exércitos; e neste lugar darei a paz, diz o Senhor dos exércitos.' },
      { v: 10, en: 'In the twenty-fourth day of the ninth month, in the second year of Darius, Yahweh’s word came by Haggai the prophet, saying,', pt: 'Ao vigésimo quarto dia do mês nono, no segundo ano de Dario, veio a palavra do Senhor ao profeta Ageu, dizendo:' },
      { v: 11, en: '“Yahweh of Armies says: Ask now the priests concerning the law, saying,', pt: 'Assim diz o Senhor dos exércitos: Pergunta agora aos sacerdotes, acerca da lei, dizendo:' },
      { v: 12, en: '‘If someone carries holy meat in the fold of his garment, and with his fold touches bread, stew, wine, oil, or any food, will it become holy?’” The priests answered, “No.”', pt: 'Se alguém levar na aba de suas vestes carne santa, e com a sua aba tocar no pão, ou no guisado, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará este santificado? E os sacerdotes responderam: Não.' },
      { v: 13, en: 'Then Haggai said, “If one who is unclean by reason of a dead body touch any of these, will it be unclean?” The priests answered, “It will be unclean.”', pt: 'Então perguntou Ageu: Se alguém, que for contaminado pelo contato com o corpo morto, tocar nalguma destas coisas, ficará ela imunda? E os sacerdotes responderam: Ficará imunda.' },
      { v: 14, en: 'Then Haggai answered, “‘So is this people, and so is this nation before me,’ says Yahweh; ‘and so is every work of their hands. That which they offer there is unclean.', pt: 'Ao que respondeu Ageu, dizendo: Assim é este povo, e assim é esta nação diante de mim, diz o Senhor; assim é toda a obra das suas mãos; e tudo o que ali oferecem imundo é.' },
      { v: 15, en: 'Now, please consider from this day and backward, before a stone was laid on a stone in Yahweh’s temple.', pt: 'Agora considerai o que acontece desde aquele dia. Antes que se lançasse pedra sobre pedra no templo do Senhor,' },
      { v: 16, en: 'Through all that time, when one came to a heap of twenty measures, there were only ten. When one came to the wine vat to draw out fifty, there were only twenty.', pt: 'quando alguém vinha a um montão de trigo de vinte medidas, havia somente dez; quando vinha ao lagar para tirar cinqüenta, havia somente vinte.' },
      { v: 17, en: 'I struck you with blight, mildew, and hail in all the work of your hands; yet you didn’t turn to me,’ says Yahweh.', pt: 'Feri-vos com mangra, e com ferrugem, e com saraiva, em todas as obras das vossas mãos; e não houve entre vós quem voltasse para mim, diz o Senhor.' },
      { v: 18, en: '‘Consider, please, from this day and backward, from the twenty-fourth day of the ninth month, since the day that the foundation of Yahweh’s temple was laid, consider it.', pt: 'Considerai, pois, eu vos rogo, desde este dia em diante, desde o vigésimo quarto dia do mês nono, desde o dia em que se lançaram os alicerces do templo do Senhor, sim, considerai essas coisas.' },
      { v: 19, en: 'Is the seed yet in the barn? Yes, the vine, the fig tree, the pomegranate, and the olive tree haven’t produced. From today I will bless you.’”', pt: 'Está ainda semente no celeiro? A videira, a figueira, a romeira, e a oliveira ainda não dão os seus frutos? Desde este dia hei de vos abençoar.' },
      { v: 20, en: 'Yahweh’s word came the second time to Haggai in the twenty-fourth day of the month, saying,', pt: 'Veio pela segunda vez a palavra do Senhor a Ageu, aos vinte e quatro do mês, dizendo:' },
      { v: 21, en: '“Speak to Zerubbabel, governor of Judah, saying, ‘I will shake the heavens and the earth.', pt: 'Fala a Zorobabel, governador de Judá, dizendo: Abalarei os céus e a terra;' },
      { v: 22, en: 'I will overthrow the throne of kingdoms. I will destroy the strength of the kingdoms of the nations. I will overthrow the chariots, and those who ride in them. The horses and their riders will come down, everyone by the sword of his brother.', pt: 'e derrubarei o trono dos reinos, e destruirei a força dos reinos das nações; destruirei o carro e os que nele andam; os cavalos e os seus cavaleiros cairão, cada um pela espada do seu irmão.' },
      { v: 23, en: 'In that day, says Yahweh of Armies, will I take you, Zerubbabel, my servant, the son of Shealtiel,’ says Yahweh, ‘and will make you as a signet, for I have chosen you,’ says Yahweh of Armies.”', pt: 'Naquele dia, diz o Senhor dos exércitos, tomar-te-ei, ó Zorobabel, servo meu, filho de Sealtiel, diz o Senhor, e te farei como um anel de selar; porque te escolhi, diz o Senhor dos exércitos.' },
    ],
  },
};

export default book;
