import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: 'jonah',
  name: 'Jonas',
  englishName: 'Jonah',
  testament: 'old',
  chapters: {
    1: [
      { v: 1, en: 'Now Yahweh’s word came to Jonah the son of Amittai, saying,', pt: 'Ora veio a palavra do Senhor a Jonas, filho de Amitai, dizendo:' },
      { v: 2, en: '“Arise, go to Nineveh, that great city, and preach against it, for their wickedness has come up before me.”', pt: 'Levanta-te, vai à grande cidade de Nínive, e clama contra ela, porque a sua malícia subiu até mim.' },
      { v: 3, en: 'But Jonah rose up to flee to Tarshish from the presence of Yahweh. He went down to Joppa, and found a ship going to Tarshish; so he paid its fare, and went down into it, to go with them to Tarshish from the presence of Yahweh.', pt: 'Jonas, porém, levantou-se para fugir da presença do Senhor para Társis. E, descendo a Jope, achou um navio que ia para Társis; pagou, pois, a sua passagem, e desceu para dentro dele, para ir com eles para Társis, da presença do Senhor.' },
      { v: 4, en: 'But Yahweh sent out a great wind on the sea, and there was a mighty storm on the sea, so that the ship was likely to break up.', pt: 'Mas o Senhor lançou sobre o mar um grande vento, e fez-se no mar uma grande tempestade, de modo que o navio estava a ponto de se despedaçar.' },
      { v: 5, en: 'Then the mariners were afraid, and every man cried to his god. They threw the cargo that was in the ship into the sea to lighten the ship. But Jonah had gone down into the innermost parts of the ship, and he was laying down, and was fast asleep.', pt: 'Então os marinheiros tiveram medo, e clamavam cada um ao seu deus, e alijaram ao mar a carga que estava no navio, para o aliviarem; Jonas, porém, descera ao porão do navio; e, tendo-se deitado, dormia um profundo sono.' },
      { v: 6, en: 'So the ship master came to him, and said to him, “What do you mean, sleeper? Arise, call on your God! Maybe your God will notice us, so that we won’t perish.”', pt: 'O mestre do navio, pois, chegou-se a ele, e disse-lhe: Que estás fazendo, ó tu que dormes? Levanta-te, clama ao teu deus; talvez assim ele se lembre de nós, para que não pereçamos.' },
      { v: 7, en: 'They all said to each other, “Come, let us cast lots, that we may know who is responsible for this evil that is on us.” So they cast lots, and the lot fell on Jonah.', pt: 'E dizia cada um ao seu companheiro: Vinde, e lancemos sortes, para sabermos por causa de quem nos sobreveio este mal. E lançaram sortes, e a sorte caiu sobre Jonas.' },
      { v: 8, en: 'Then they asked him, “Tell us, please, for whose cause this evil is on us. What is your occupation? Where do you come from? What is your country? Of what people are you?”', pt: 'Então lhe disseram: Declara-nos tu agora, por causa de quem nos sobreveio este mal. Que ocupação é a tua? Donde vens? Qual é a tua terra? E de que povo és tu?' },
      { v: 9, en: 'He said to them, “I am a Hebrew, and I fear Yahweh, the God of heaven, who has made the sea and the dry land.”', pt: 'Respondeu-lhes ele: Eu sou hebreu, e temo ao Senhor, o Deus do céu, que fez o mar e a terra seca.' },
      { v: 10, en: 'Then the men were exceedingly afraid, and said to him, “What have you done?” For the men knew that he was fleeing from the presence of Yahweh, because he had told them.', pt: 'Então estes homens se encheram de grande temor, e lhe disseram: Que é isso que fizeste? pois sabiam os homens que fugia da presença do Senhor, porque ele lho tinha declarado.' },
      { v: 11, en: 'Then they said to him, “What shall we do to you, that the sea may be calm to us?” For the sea grew more and more stormy.', pt: 'Ainda lhe perguntaram: Que te faremos nós, para que o mar se nos acalme? Pois o mar se ia tornando cada vez mais tempestuoso.' },
      { v: 12, en: 'He said to them, “Take me up, and throw me into the sea. Then the sea will be calm for you; for I know that because of me this great storm is on you.”', pt: 'Respondeu-lhes ele: Levantai-me, e lançai-me ao mar, e o mar se vos aquietará; porque eu sei que por minha causa vos sobreveio esta grande tempestade.' },
      { v: 13, en: 'Nevertheless the men rowed hard to get them back to the land; but they could not, for the sea grew more and more stormy against them.', pt: 'Entretanto os homens se esforçavam com os remos para tornar a alcançar a terra; mas não podiam, porquanto o mar se ia embravecendo cada vez mais contra eles.' },
      { v: 14, en: 'Therefore they cried to Yahweh, and said, “We beg you, Yahweh, we beg you, don’t let us die for this man’s life, and don’t lay on us innocent blood; for you, Yahweh, have done as it pleased you.”', pt: 'Por isso clamaram ao Senhor, e disseram: Nós te rogamos, ó Senhor, que não pereçamos por causa da vida deste homem, e que não ponhas sobre nós o sangue inocente; porque tu, Senhor, fizeste como te aprouve.' },
      { v: 15, en: 'So they took up Jonah, and threw him into the sea; and the sea ceased its raging.', pt: 'Então levantaram a Jonas, e o lançaram ao mar; e cessou o mar da sua fúria.' },
      { v: 16, en: 'Then the men feared Yahweh exceedingly; and they offered a sacrifice to Yahweh, and made vows.', pt: 'Temeram, pois, os homens ao Senhor com grande temor; e ofereceram sacrifícios ao Senhor, e fizeram votos.' },
      { v: 17, en: 'Yahweh prepared a great fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three nights.', pt: 'Então o Senhor deparou um grande peixe, para que tragasse a Jonas; e esteve Jonas três dias e três noites nas entranhas do peixe.' },
    ],
    2: [
      { v: 1, en: 'Then Jonah prayed to Yahweh, his God, out of the fish’s belly.', pt: 'E orou Jonas ao Senhor, seu Deus, lá das entranhas do peixe;' },
      { v: 2, en: 'He said, “I called because of my affliction to Yahweh. He answered me. Out of the belly of Sheol I cried. You heard my voice.', pt: 'e disse: Na minha angústia clamei ao senhor, e ele me respondeu; do ventre do Seol gritei, e tu ouviste a minha voz.' },
      { v: 3, en: 'For you threw me into the depths, in the heart of the seas. The flood was all around me. All your waves and your billows passed over me.', pt: 'Pois me lançaste no profundo, no coração dos mares, e a corrente das águas me cercou; todas as tuas ondas e as tuas vagas passaram por cima de mim.' },
      { v: 4, en: 'I said, ‘I have been banished from your sight; yet I will look again toward your holy temple.’', pt: 'E eu disse: Lançado estou de diante dos teus olhos; como tornarei a olhar para o teu santo templo?' },
      { v: 5, en: 'The waters surrounded me, even to the soul. The deep was around me. The weeds were wrapped around my head.', pt: 'As águas me cercaram até a alma, o abismo me rodeou, e as algas se enrolaram na minha cabeça.' },
      { v: 6, en: 'I went down to the bottoms of the mountains. The earth barred me in forever: yet have you brought up my life from the pit, Yahweh my God.', pt: 'Eu desci até os fundamentos dos montes; a terra encerrou-me para sempre com os seus ferrolhos; mas tu, Senhor meu Deus, fizeste subir da cova a minha vida.' },
      { v: 7, en: '“When my soul fainted within me, I remembered Yahweh. My prayer came in to you, into your holy temple.', pt: 'Quando dentro de mim desfalecia a minha alma, eu me lembrei do Senhor; e entrou a ti a minha oração, no teu santo templo.' },
      { v: 8, en: 'Those who regard lying vanities forsake their own mercy.', pt: 'Os que se apegam aos vãos ídolos afastam de si a misericórdia.' },
      { v: 9, en: 'But I will sacrifice to you with the voice of thanksgiving. I will pay that which I have vowed. Salvation belongs to Yahweh.”', pt: 'Mas eu te oferecerei sacrifício com a voz de ação de graças; o que votei pagarei. Ao Senhor pertence a salvação.' },
      { v: 10, en: 'Then Yahweh spoke to the fish, and it vomited out Jonah on the dry land.', pt: 'Falou, pois, o Senhor ao peixe, e o peixe vomitou a Jonas na terra.' },
    ],
    3: [
      { v: 1, en: 'Yahweh’s word came to Jonah the second time, saying,', pt: 'Pela segunda vez veio a palavra do Senhor a Jonas, dizendo:' },
      { v: 2, en: '“Arise, go to Nineveh, that great city, and preach to it the message that I give you.”', pt: 'Levanta-te, e vai à grande cidade de Nínive, e lhe proclama a mensagem que eu te ordeno.' },
      { v: 3, en: 'So Jonah arose, and went to Nineveh, according to Yahweh’s word. Now Nineveh was an exceedingly great city, three days’ journey across.', pt: 'Levantou-se, pois, Jonas, e foi a Nínive, segundo a palavra do Senhor. Ora, Nínive era uma grande cidade, de três dias de jornada.' },
      { v: 4, en: 'Jonah began to enter into the city a day’s journey, and he cried out, and said, “In forty days, Nineveh will be overthrown!”', pt: 'E começou Jonas a entrar pela cidade, fazendo a jornada dum dia, e clamava, dizendo: Ainda quarenta dias, e Nínive será subvertida.' },
      { v: 5, en: 'The people of Nineveh believed God; and they proclaimed a fast, and put on sackcloth, from their greatest even to their least.', pt: 'E os homens de Nínive creram em Deus; e proclamaram um jejum, e vestiram-se de saco, desde o maior deles até o menor.' },
      { v: 6, en: 'The news reached the king of Nineveh, and he arose from his throne, and took off his royal robe, covered himself with sackcloth, and sat in ashes.', pt: 'A notícia chegou também ao rei de Nínive; e ele se levantou do seu trono e, despindo-se do seu manto e cobrindo-se de saco, sentou-se sobre cinzas.' },
      { v: 7, en: 'He made a proclamation and published through Nineveh by the decree of the king and his nobles, saying, “Let neither man nor animal, herd nor flock, taste anything; let them not feed, nor drink water;', pt: 'E fez uma proclamação, e a publicou em Nínive, por decreto do rei e dos seus nobres, dizendo: Não provem coisa alguma nem homens, nem animais, nem bois, nem ovelhas; não comam, nem bebam água;' },
      { v: 8, en: 'but let them be covered with sackcloth, both man and animal, and let them cry mightily to God. Yes, let them turn everyone from his evil way, and from the violence that is in his hands.', pt: 'mas sejam cobertos de saco, tanto os homens como os animais, e clamem fortemente a Deus; e convertam-se, cada um do seu mau caminho, e da violência que há nas suas mãos.' },
      { v: 9, en: 'Who knows whether God will not turn and relent, and turn away from his fierce anger, so that we might not perish?”', pt: 'Quem sabe se se voltará Deus, e se arrependerá, e se apartará do furor da sua ira, de sorte que não pereçamos?' },
      { v: 10, en: 'God saw their works, that they turned from their evil way. God relented of the disaster which he said he would do to them, and he didn’t do it.', pt: 'Viu Deus o que fizeram, como se converteram do seu mau caminho, e Deus se arrependeu do mal que tinha dito lhes faria, e não o fez.' },
    ],
    4: [
      { v: 1, en: 'But it displeased Jonah exceedingly, and he was angry.', pt: 'Mas isso desagradou extremamente a Jonas, e ele ficou irado.' },
      { v: 2, en: 'He prayed to Yahweh, and said, “Please, Yahweh, wasn’t this what I said when I was still in my own country? Therefore I hurried to flee to Tarshish, for I knew that you are a gracious God, and merciful, slow to anger, and abundant in loving kindness, and you relent of doing harm.', pt: 'E orou ao Senhor, e disse: Ah! Senhor! não foi isso o que eu disse, estando ainda na minha terra? Por isso é que me apressei a fugir para Társis, pois eu sabia que és Deus compassivo e misericordioso, longânimo e grande em benignidade, e que te arrependes do mal.' },
      { v: 3, en: 'Therefore now, Yahweh, take, I beg you, my life from me; for it is better for me to die than to live.”', pt: 'Agora, ó Senhor, tira-me a vida, pois melhor me é morrer do que viver.' },
      { v: 4, en: 'Yahweh said, “Is it right for you to be angry?”', pt: 'Respondeu o senhor: É razoável essa tua ira?' },
      { v: 5, en: 'Then Jonah went out of the city, and sat on the east side of the city, and there made himself a booth, and sat under it in the shade, until he might see what would become of the city.', pt: 'Então Jonas saiu da cidade, e sentou-se ao oriente dela; e ali fez para si uma barraca, e se sentou debaixo dela, à sombra, até ver o que aconteceria à cidade.' },
      { v: 6, en: 'Yahweh God prepared a vine, and made it to come up over Jonah, that it might be a shade over his head, to deliver him from his discomfort. So Jonah was exceedingly glad because of the vine.', pt: 'E fez o Senhor Deus nascer uma aboboreira, e fê-la crescer por cima de Jonas, para que lhe fizesse sombra sobre a cabeça, a fim de o livrar do seu enfado; de modo que Jonas se alegrou em extremo por causa da aboboreira.' },
      { v: 7, en: 'But God prepared a worm at dawn the next day, and it chewed on the vine, so that it withered.', pt: 'Mas Deus enviou um bicho, no dia seguinte ao subir da alva, o qual feriu a aboboreira, de sorte que esta se secou.' },
      { v: 8, en: 'When the sun arose, God prepared a sultry east wind; and the sun beat on Jonah’s head, so that he fainted, and requested for himself that he might die, and said, “It is better for me to die than to live.”', pt: 'E aconteceu que, aparecendo o sol, Deus mandou um vento calmoso oriental; e o sol bateu na cabeça de Jonas, de maneira que ele desmaiou, e desejou com toda a sua alma morrer, dizendo: Melhor me é morrer do que viver.' },
      { v: 9, en: 'God said to Jonah, “Is it right for you to be angry about the vine?” He said, “I am right to be angry, even to death.”', pt: 'Então perguntou Deus a Jonas: É razoável essa tua ira por causa da aboboreira? Respondeu ele: É justo que eu me enfade a ponto de desejar a morte.' },
      { v: 10, en: 'Yahweh said, “You have been concerned for the vine, for which you have not labored, neither made it grow; which came up in a night, and perished in a night.', pt: 'Disse, pois, o Senhor: Tens compaixão da aboboreira, na qual não trabalhaste, nem a fizeste crescer; que numa noite nasceu, e numa noite pereceu.' },
      { v: 11, en: 'Shouldn’t I be concerned for Nineveh, that great city, in which are more than one hundred twenty thousand persons who can’t discern between their right hand and their left hand; and also much livestock?”', pt: 'E não hei de eu ter compaixão da grande cidade de Nínive em que há mais de cento e vinte mil pessoas que não sabem discernir entre a sua mão direita e a esquerda, e também muito gado?' },
    ],
  },
};

export default book;
