import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: 'malachi',
  name: 'Malaquias',
  englishName: 'Malachi',
  testament: 'old',
  chapters: {
    1: [
      { v: 1, en: 'A revelation, Yahweh’s word to Israel by Malachi.', pt: 'A palavra do Senhor a Israel, por intermédio de Malaquias.' },
      { v: 2, en: '“I have loved you,” says Yahweh. Yet you say, “How have you loved us?” “Wasn’t Esau Jacob’s brother?” says Yahweh, “Yet I loved Jacob;', pt: 'Eu vos tenho amado, diz o Senhor. Mas vós dizeis: Em que nos tens amado? Acaso não era Esaú irmão de Jacó? diz o Senhor; todavia amei a Jacó,' },
      { v: 3, en: 'but Esau I hated, and made his mountains a desolation, and gave his heritage to the jackals of the wilderness.”', pt: 'e aborreci a Esaú; e fiz dos seus montes uma desolação, e dei a sua herança aos chacais do deserto.' },
      { v: 4, en: 'Whereas Edom says, “We are beaten down, but we will return and build the waste places”; Yahweh of Armies says, “They shall build, but I will throw down; and men will call them ‘The Wicked Land,’ even the people against whom Yahweh shows wrath forever.”', pt: 'Ainda que Edom diga: Arruinados estamos, porém tornaremos e edificaremos as ruínas; assim diz o Senhor dos exércitos: Eles edificarão, eu, porém, demolirei; e lhes chamarão: Termo de impiedade, e povo contra quem o Senhor está irado para sempre.' },
      { v: 5, en: 'Your eyes will see, and you will say, “Yahweh is great—even beyond the border of Israel!”', pt: 'E os vossos olhos o verão, e direis: Engrandecido é o Senhor ainda além dos termos de Israel.' },
      { v: 6, en: '“A son honors his father, and a servant his master. If I am a father, then where is my honor? And if I am a master, where is the respect due me? Says Yahweh of Armies to you, priests, who despise my name. You say, ‘How have we despised your name?’', pt: 'O filho honra o pai, e o servo ao seu amo; se eu, pois, sou pai, onde está a minha honra? e se eu sou amo, onde está o temor de mim? diz o Senhor dos exércitos a vós, ó sacerdotes, que desprezais o meu nome. E vós dizeis: Em que temos nós desprezado o teu nome?' },
      { v: 7, en: 'You offer polluted bread on my altar. You say, ‘How have we polluted you?’ In that you say, ‘Yahweh’s table is contemptible.’', pt: 'Ofereceis sobre o meu altar pão profano, e dizeis: Em que te havemos profanado? Nisto que pensais, que a mesa do Senhor é desprezível.' },
      { v: 8, en: 'When you offer the blind for sacrifice, isn’t that evil? And when you offer the lame and sick, isn’t that evil? Present it now to your governor! Will he be pleased with you? Or will he accept your person?” says Yahweh of Armies.', pt: 'Pois quando ofereceis em sacrifício um animal cego, isso não é mau? E quando ofereceis o coxo ou o doente, isso não é mau? Ora apresenta-o ao teu governador; terá ele agrado em ti? ou aceitará ele a tua pessoa? diz o Senhor dos exércitos.' },
      { v: 9, en: '“Now, please entreat the favor of God, that he may be gracious to us. With this, will he accept any of you?” says Yahweh of Armies.', pt: 'Agora, pois, suplicai o favor de Deus, para que se compadeça de nós. Com tal oferta da vossa mão, aceitará ele a vossa pessoa? diz o Senhor dos exércitos.' },
      { v: 10, en: '“Oh that there were one among you who would shut the doors, that you might not kindle fire on my altar in vain! I have no pleasure in you,” says Yahweh of Armies, “neither will I accept an offering at your hand.', pt: 'Oxalá que entre vós houvesse até um que fechasse as portas para que não acendesse debalde o fogo do meu altar. Eu não tenho prazer em vós, diz o Senhor dos exércitos, nem aceitarei oferta da vossa mão.' },
      { v: 11, en: 'For from the rising of the sun even to the going down of the same, my name is great among the nations, and in every place incense will be offered to my name, and a pure offering: for my name is great among the nations,” says Yahweh of Armies.', pt: 'Mas desde o nascente do sol até o poente é grande entre as nações o meu nome; e em todo lugar se oferece ao meu nome incenso, e uma oblação pura; porque o meu nome é grande entre as nações, diz o Senhor dos exércitos.' },
      { v: 12, en: '“But you profane it, in that you say, ‘Yahweh’s table is polluted, and its fruit, even its food, is contemptible.’', pt: 'Mas vós o profanais, quando dizeis: A mesa do Senhor é profana, e o seu produto, isto é, a sua comida, é desprezível.' },
      { v: 13, en: 'You say also, ‘Behold, what a weariness it is!’ and you have sniffed at it”, says Yahweh of Armies; “and you have brought that which was taken by violence, the lame, and the sick; thus you bring the offering. Should I accept this at your hand?” says Yahweh.', pt: 'Dizeis também: Eis aqui, que canseira! e o lançastes ao desprezo, diz o Senhor dos exércitos; e tendes trazido o que foi roubado, e o coxo e o doente; assim trazeis a oferta. Aceitaria eu isso de vossa mão? diz o Senhor.' },
      { v: 14, en: '“But the deceiver is cursed, who has in his flock a male, and vows, and sacrifices to the Lord a defective thing; for I am a great King,” says Yahweh of Armies, “and my name is awesome among the nations.”', pt: 'Mas seja maldito o enganador que, tendo animal macho no seu rebanho, o vota, e sacrifica ao Senhor o que tem mácula; porque eu sou grande Rei, diz o Senhor dos exércitos, e o meu nome é temível entre as nações.' },
    ],
    2: [
      { v: 1, en: '“Now, you priests, this commandment is for you.', pt: 'Agora, ó sacerdotes, este mandamento e para vós.' },
      { v: 2, en: 'If you will not listen, and if you will not take it to heart, to give glory to my name,” says Yahweh of Armies, “then will I send the curse on you, and I will curse your blessings. Indeed, I have cursed them already, because you do not take it to heart.', pt: 'Se não ouvirdes, e se não propuserdes no vosso coração dar honra ao meu nome, diz o Senhor dos exércitos, enviarei a maldição contra vós, e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque não aplicais a isso o vosso coração.' },
      { v: 3, en: 'Behold, I will rebuke your offspring, and will spread dung on your faces, even the dung of your feasts; and you will be taken away with it.', pt: 'Eis que vos reprovarei a posteridade, e espalharei sobre os vossos rostos o esterco, sim, o esterco dos vossos sacrifícios; e juntamente com este sereis levados para fora.' },
      { v: 4, en: 'You will know that I have sent this commandment to you, that my covenant may be with Levi,” says Yahweh of Armies.', pt: 'Então sabereis que eu vos enviei este mandamento, para que o meu pacto fosse com Levi, diz o Senhor dos exércitos.' },
      { v: 5, en: '“My covenant was with him of life and peace; and I gave them to him that he might be reverent toward me; and he was reverent toward me, and stood in awe of my name.', pt: 'Meu pacto com ele foi de vida e de paz; e eu lhas dei para que me temesse; e ele me temeu, e assombrou-se por causa do meu nome.' },
      { v: 6, en: 'The law of truth was in his mouth, and unrighteousness was not found in his lips. He walked with me in peace and uprightness, and turned many away from iniquity.', pt: 'A lei da verdade esteve na sua boca, e a impiedade não se achou nos seus lábios; ele andou comigo em paz e em retidão, e da iniqüidade apartou a muitos.' },
      { v: 7, en: 'For the priest’s lips should keep knowledge, and they should seek the law at his mouth; for he is the messenger of Yahweh of Armies.', pt: 'Pois os lábios do sacerdote devem guardar o conhecimento, e da sua boca devem os homens procurar a instrução, porque ele é o mensageiro do Senhor dos exércitos.' },
      { v: 8, en: 'But you have turned away from the path. You have caused many to stumble in the law. You have corrupted the covenant of Levi,” says Yahweh of Armies.', pt: 'Mas vós vos desviastes do caminho; a muitos fizestes tropeçar na lei; corrompestes o pacto de Levi, diz o Senhor dos exércitos.' },
      { v: 9, en: '“Therefore I have also made you contemptible and wicked before all the people, according to the way you have not kept my ways, but have had respect for persons in the law.', pt: 'Por isso também eu vos fiz desprezíveis, e indignos diante de todo o povo, visto que não guardastes os meus caminhos, mas fizestes acepção de pessoas na lei.' },
      { v: 10, en: 'Don’t we all have one father? Hasn’t one God created us? Why do we deal treacherously every man against his brother, profaning the covenant of our fathers?', pt: 'Não temos nós todos um mesmo Pai? não nos criou um mesmo Deus? por que nos havemos aleivosamente uns para com outros, profanando o pacto de nossos pais?' },
      { v: 11, en: 'Judah has dealt treacherously, and an abomination is committed in Israel and in Jerusalem; for Judah has profaned the holiness of Yahweh which he loves, and has married the daughter of a foreign god.', pt: 'Judá se tem havido aleivosamente, e abominação se cometeu em Israel e em Jerusalém; porque Judá profanou o santuario do Senhor, o qual ele ama, e se casou com a filha de deus estranho.' },
      { v: 12, en: 'Yahweh will cut off, to the man who does this, him who wakes and him who answers, out of the tents of Jacob, and him who offers an offering to Yahweh of Armies.', pt: 'O Senhor extirpará das tendas de Jacó o homem que fizer isto, o que vela, e o que responde, e o que oferece dons ao Senhor dos exércitos.' },
      { v: 13, en: 'This again you do: you cover Yahweh’s altar with tears, with weeping, and with sighing, because he doesn’t regard the offering any more, neither receives it with good will at your hand.', pt: 'Ainda fazeis isto: cobris o altar do Senhor de lágrimas, de choros e de gemidos, porque ele não olha mais para a oferta, nem a aceitará com prazer da vossa mão.' },
      { v: 14, en: 'Yet you say, ‘Why?’ Because Yahweh has been witness between you and the wife of your youth, against whom you have dealt treacherously, though she is your companion, and the wife of your covenant.', pt: 'Todavia perguntais: Por que? Porque o Senhor tem sido testemunha entre ti e a mulher da tua mocidade, para com a qual procedeste deslealmente sendo ela a tua companheira e a mulher da tua aliança.' },
      { v: 15, en: 'Did he not make you one, although he had the residue of the Spirit? Why one? He sought godly offspring. Therefore take heed to your spirit, and let no one deal treacherously against the wife of his youth.', pt: 'E não fez ele somente um, ainda que lhe sobejava espírito? E por que somente um? Não é que buscava descendência piedosa? Portanto guardai-vos em vosso espírito, e que ninguém seja infiel para com a mulher da sua mocidade.' },
      { v: 16, en: 'For I hate divorce”, says Yahweh, the God of Israel, “and him who covers his garment with violence!” says Yahweh of Armies. “Therefore take heed to your spirit, that you don’t deal treacherously.', pt: 'Pois eu detesto o divórcio, diz o Senhor Deus de Israel, e aquele que cobre de violência o seu vestido; portanto cuidai de vós mesmos, diz o Senhor dos exércitos; e não sejais infiéis.' },
      { v: 17, en: 'You have wearied Yahweh with your words. Yet you say, ‘How have we wearied him?’ In that you say, ‘Everyone who does evil is good in Yahweh’s sight, and he delights in them;’ or ‘Where is the God of justice?’', pt: 'Tendes enfadado ao Senhor com vossas palavras; e ainda dizeis: Em que o havemos enfadado? Nisto que dizeis: Qualquer que faz o mal passa por bom aos olhos do Senhor, e desses é que ele se agrada; ou: Onde está o Deus do juízo?' },
    ],
    3: [
      { v: 1, en: '“Behold, I send my messenger, and he will prepare the way before me; and the Lord, whom you seek, will suddenly come to his temple; and the messenger of the covenant, whom you desire, behold, he comes!” says Yahweh of Armies.', pt: 'Eis que eu envio o meu mensageiro, e ele há de preparar o caminho diante de mim; e de repente virá ao seu templo o Senhor, a quem vós buscais, e o anjo do pacto, a quem vós desejais; eis que ele vem, diz o Senhor dos exércitos.' },
      { v: 2, en: '“But who can endure the day of his coming? And who will stand when he appears? For he is like a refiner’s fire, and like launderers’ soap;', pt: 'Mas quem suportará o dia da sua vinda? e quem subsistirá, quando ele aparecer? Pois ele será como o fogo de fundidor e como o sabão de lavandeiros;' },
      { v: 3, en: 'and he will sit as a refiner and purifier of silver, and he will purify the sons of Levi, and refine them as gold and silver; and they shall offer to Yahweh offerings in righteousness.', pt: 'assentar-se-á como fundidor e purificador de prata; e purificará os filhos de Levi, e os refinará como ouro e como prata, até que tragam ao Senhor ofertas em justiça.' },
      { v: 4, en: 'Then the offering of Judah and Jerusalem will be pleasant to Yahweh, as in the days of old, and as in ancient years.', pt: 'Então a oferta de Judá e de Jerusalém será agradável ao Senhor, como nos dias antigos, e como nos primeiros anos.' },
      { v: 5, en: 'I will come near to you to judgment; and I will be a swift witness against the sorcerers, and against the adulterers, and against the perjurers, and against those who oppress the hireling in his wages, the widow, and the fatherless, and who deprive the foreigner of justice, and don’t fear me,” says Yahweh of Armies.', pt: 'E chegar-me-ei a vós para juízo; e serei uma testemunha veloz contra os feiticeiros, contra os adúlteros, contra os que juram falsamente, contra os que defraudam o trabalhador em seu salário, a viúva, e o órfão, e que pervertem o direito do estrangeiro, e não me temem, diz o Senhor dos exércitos.' },
      { v: 6, en: '“For I, Yahweh, don’t change; therefore you, sons of Jacob, are not consumed.', pt: 'Pois eu, o Senhor, não mudo; por isso vós, ó filhos de Jacó, não sois consumidos.' },
      { v: 7, en: 'From the days of your fathers you have turned away from my ordinances, and have not kept them. Return to me, and I will return to you,” says Yahweh of Armies. “But you say, ‘How shall we return?’', pt: 'Desde os dias de vossos pais vos desviastes dos meus estatutos, e não os guardastes. Tornai vós para mim, e eu tornarei para vós diz o Senhor dos exércitos. Mas vós dizeis: Em que havemos de tornar?' },
      { v: 8, en: 'Will a man rob God? Yet you rob me! But you say, ‘How have we robbed you?’ In tithes and offerings.', pt: 'Roubará o homem a Deus? Todavia vós me roubais, e dizeis: Em que te roubamos? Nos dízimos e nas ofertas alçadas.' },
      { v: 9, en: 'You are cursed with the curse; for you rob me, even this whole nation.', pt: 'Vós sois amaldiçoados com a maldição; porque a mim me roubais, sim, vós, esta nação toda.' },
      { v: 10, en: 'Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this,” says Yahweh of Armies, “if I will not open you the windows of heaven, and pour you out a blessing, that there will not be room enough for.', pt: 'Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos exércitos, se eu não vos abrir as janelas do céu, e não derramar sobre vós tal bênção, que dela vos advenha a maior abastança.' },
      { v: 11, en: 'I will rebuke the devourer for your sakes, and he shall not destroy the fruits of your ground; neither shall your vine cast its fruit before its time in the field,” says Yahweh of Armies.', pt: 'Também por amor de vós reprovarei o devorador, e ele não destruirá os frutos da vossa terra; nem a vossa vide no campo lançará o seu fruto antes do tempo, diz o Senhor dos exércitos.' },
      { v: 12, en: '“All nations shall call you blessed, for you will be a delightful land,” says Yahweh of Armies.', pt: 'E todas as nações vos chamarão bem-aventurados; porque vós sereis uma terra deleitosa, diz o Senhor dos exércitos.' },
      { v: 13, en: '“Your words have been stout against me,” says Yahweh. “Yet you say, ‘What have we spoken against you?’', pt: 'As vossas palavras foram agressivas para mim, diz o Senhor. Mas vós dizeis: Que temos falado contra ti?' },
      { v: 14, en: 'You have said, ‘It is vain to serve God;’ and ‘What profit is it that we have followed his instructions, and that we have walked mournfully before Yahweh of Armies?', pt: 'Vós tendes dito: lnútil é servir a Deus. Que nos aproveita termos cuidado em guardar os seus preceitos, e em andar de luto diante do Senhor dos exércitos?' },
      { v: 15, en: 'Now we call the proud happy; yes, those who work wickedness are built up; yes, they tempt God, and escape.’', pt: 'Ora pois, nós reputamos por bem-aventurados os soberbos; também os que cometem impiedade prosperam; sim, eles tentam a Deus, e escapam.' },
      { v: 16, en: 'Then those who feared Yahweh spoke one with another; and Yahweh listened, and heard, and a book of memory was written before him, for those who feared Yahweh, and who honored his name.', pt: 'Então aqueles que temiam ao Senhor falaram uns aos outros; e o Senhor atentou e ouviu, e um memorial foi escrito diante dele, para os que temiam ao Senhor, e para os que se lembravam do seu nome.' },
      { v: 17, en: 'They shall be mine,” says Yahweh of Armies, “my own possession in the day that I make, and I will spare them, as a man spares his own son who serves him.', pt: 'E eles serão meus, diz o Senhor dos exércitos, minha possessão particular naquele dia que prepararei; poupá-los-ei, como um homem poupa a seu filho, que o serve.' },
      { v: 18, en: 'Then you shall return and discern between the righteous and the wicked, between him who serves God and him who doesn’t serve him.', pt: 'Então vereis outra vez a diferença entre o justo e o ímpio; entre o que serve a Deus, e o que o não serve.' },
    ],
    4: [
      { v: 1, en: '“For, behold, the day comes, it burns as a furnace; and all the proud, and all who work wickedness, will be stubble; and the day that comes will burn them up,” says Yahweh of Armies, “that it shall leave them neither root nor branch.', pt: 'Pois eis que aquele dia vem ardendo como fornalha; todos os soberbos, e todos os que cometem impiedade, serão como restolho; e o dia que está para vir os abrasará, diz o Senhor dos exércitos, de sorte que não lhes deixará nem raiz nem ramo.' },
      { v: 2, en: 'But to you who fear my name shall the sun of righteousness arise with healing in its wings. You will go out, and leap like calves of the stall.', pt: 'Mas para vós, os que temeis o meu nome, nascerá o sol da justiça, trazendo curas nas suas asas; e vós saireis e saltareis como bezerros da estrebaria.' },
      { v: 3, en: 'You shall tread down the wicked; for they will be ashes under the soles of your feet in the day that I make,” says Yahweh of Armies.', pt: 'E pisareis os ímpios, porque se farão cinza debaixo das plantas de vossos pés naquele dia que prepararei, diz o Senhor dos exércitos.' },
      { v: 4, en: '“Remember the law of Moses my servant, which I commanded to him in Horeb for all Israel, even statutes and ordinances.', pt: 'Lembrai-vos da lei de Moisés, meu servo, a qual lhe mandei em Horebe para todo o Israel, a saber, estatutos e ordenanças.' },
      { v: 5, en: 'Behold, I will send you Elijah the prophet before the great and terrible day of Yahweh comes.', pt: 'Eis que eu vos enviarei o profeta Elias, antes que venha o grande e terrível dia do Senhor;' },
      { v: 6, en: 'He will turn the hearts of the fathers to the children, and the hearts of the children to their fathers, lest I come and strike the earth with a curse.”', pt: 'e ele converterá o coração dos pais aos filhos, e o coração dos filhos a seus pais; para que eu não venha, e fira a terra com maldição.' },
    ],
  },
};

export default book;
