import type { BibleBook } from '../bibleData';

// Auto-generated from public-domain sources: World English Bible (WEB, EN)
// and João Ferreira de Almeida (Almeida, PT), via seven1m/open-bibles (USFX).
// Do not edit by hand — regenerate with scripts/generate-bible.

const book: BibleBook = {
  id: 'nahum',
  name: 'Naum',
  englishName: 'Nahum',
  testament: 'old',
  chapters: {
    1: [
      { v: 1, en: 'A revelation about Nineveh. The book of the vision of Nahum the Elkoshite.', pt: 'Oráculo acerca de Nínive. Livro da visão de Naum, o elcosita.' },
      { v: 2, en: 'Yahweh is a jealous God and avenges. Yahweh avenges and is full of wrath. Yahweh takes vengeance on his adversaries, and he maintains wrath against his enemies.', pt: 'O Senhor é um Deus zeloso e vingador; o Senhor é vingador e cheio de indignação; o Senhor toma vingança contra os seus adversários, e guarda a ira contra os seus inimigos.' },
      { v: 3, en: 'Yahweh is slow to anger, and great in power, and will by no means leave the guilty unpunished. Yahweh has his way in the whirlwind and in the storm, and the clouds are the dust of his feet.', pt: 'O Senhor é tardio em irar-se, e de grande poder, e ao culpado de maneira alguma terá por inocente; o Senhor tem o seu caminho no turbilhão e na tempestade, e as nuvens sao o po dos seus pes.' },
      { v: 4, en: 'He rebukes the sea, and makes it dry, and dries up all the rivers. Bashan languishes, and Carmel; and the flower of Lebanon languishes.', pt: 'Ele repreende o mar, e o faz secar, e esgota todos os rios; desfalecem Basã e Carmelo, e a flor do Líbano murcha.' },
      { v: 5, en: 'The mountains quake before him, and the hills melt away. The earth trembles at his presence, yes, the world, and all who dwell in it.', pt: 'Os montes tremem perante ele, e os outeiros se derretem; e a terra fica devastada diante dele, sim, o mundo, e todos os que nele habitam.' },
      { v: 6, en: 'Who can stand before his indignation? Who can endure the fierceness of his anger? His wrath is poured out like fire, and the rocks are broken apart by him.', pt: 'Quem pode manter-se diante do seu furor? e quem pode subsistir diante do ardor da sua ira? a sua cólera se derramou como um fogo, e por ele as rochas sao fendidas.' },
      { v: 7, en: 'Yahweh is good, a stronghold in the day of trouble; and he knows those who take refuge in him.', pt: 'O Senhor é bom, uma fortaleza no dia da angústia; e conhece os que nele confiam.' },
      { v: 8, en: 'But with an overflowing flood, he will make a full end of her place, and will pursue his enemies into darkness.', pt: 'E com uma inundação transbordante acabará duma vez com o lugar dela; e até para dentro das trevas perseguirá os seus inimigos.' },
      { v: 9, en: 'What do you plot against Yahweh? He will make a full end. Affliction won’t rise up the second time.', pt: 'Que é o que projetais vós contra o Senhor? Ele destruirá de vez; não se levantará por duas vezes a angústia.' },
      { v: 10, en: 'For entangled like thorns, and drunken as with their drink, they are consumed utterly like dry stubble.', pt: 'Pois ainda que eles se entrelacem como os espinhos, e se saturem de vinho como bêbados, serão inteiramente consumidos como restolho seco.' },
      { v: 11, en: 'There is one gone out of you, who devises evil against Yahweh, who counsels wickedness.', pt: 'Não saiu de ti um que maquinava o mal contra o Senhor, aconselhando maldade?' },
      { v: 12, en: 'Yahweh says: “Though they be in full strength, and likewise many, even so they will be cut down, and he shall pass away. Though I have afflicted you, I will afflict you no more.', pt: 'Assim diz o Senhor: Por mais intatos que sejam, e por mais numerosos, assim mesmo serão exterminados e passarão. Ainda que te afligi, não te afligirei mais.' },
      { v: 13, en: 'Now will I break his yoke from off you, and will burst your bonds apart.”', pt: 'Mas agora quebrarei o seu jugo de sobre ti, e romperei as tuas cadeias.' },
      { v: 14, en: 'Yahweh has commanded concerning you: “No more descendants will bear your name. Out of the house of your gods, will I cut off the engraved image and the molten image. I will make your grave, for you are vile.”', pt: 'Contra ti, porém, o Senhor deu ordem que não haja mais linhagem do teu nome; da casa dos teus deuses exterminarei as imagens de escultura e as de fundição; farei o teu sepulcro, porque és vil.' },
      { v: 15, en: 'Behold, on the mountains the feet of him who brings good news, who publishes peace! Keep your feasts, Judah! Perform your vows, for the wicked one will no more pass through you. He is utterly cut off.', pt: 'Eis sobre os montes os pés do que traz boas novas, do que anuncia a paz! Celebra as tuas festas, ó Judá, cumpre os teus votos, porque o ímpio não tornará mais a passar por ti; ele é inteiramente exterminado.' },
    ],
    2: [
      { v: 1, en: 'He who dashes in pieces has come up against you. Keep the fortress! Watch the way! Strengthen your waist! Fortify your power mightily!', pt: 'O destruidor sobe contra ti. Guarda tu a fortaleza, vigia o caminho, robustece os lombos, arregimenta bem as tuas forças.' },
      { v: 2, en: 'For Yahweh restores the excellency of Jacob, as the excellency of Israel; for the destroyers have destroyed them, and ruined their vine branches.', pt: 'Pois o Senhor restaura a excelência de Jacó, qual a excelência de Israel; porque os saqueadores os despojaram e destruíram os seus sarmentos.' },
      { v: 3, en: 'The shield of his mighty men is made red. The valiant men are in scarlet. The chariots flash with steel in the day of his preparation, and the pine spears are brandished.', pt: 'Os escudos dos seus valentes estão vermelhos, os homens valorosos estão vestidos de escarlate; os carros resplandecem como o aço no dia da sua preparação, e as lanças são brandidas.' },
      { v: 4, en: 'The chariots rage in the streets. They rush back and forth in the wide ways. Their appearance is like torches. They run like the lightnings.', pt: 'Os carros andam furiosamente nas ruas; cruzam as praças em todas as direções; parecem como tochas, e correm como os relampagos.' },
      { v: 5, en: 'He summons his picked troops. They stumble on their way. They dash to its wall, and the protective shield is put in place.', pt: 'Ele se lembra dos seus nobres; eles tropeçam na sua marcha; apressam-se para chegar ao muro de cidade, arma-se a manta.' },
      { v: 6, en: 'The gates of the rivers are opened, and the palace is dissolved.', pt: 'As portas dos rios abrem-se, e o palácio está em confusão.' },
      { v: 7, en: 'It is decreed: she is uncovered, she is carried away; and her servants moan as with the voice of doves, beating on their breasts.', pt: 'E está decretado: ela é despida , e levada cativa; e as suas servas gemem como pombas, batendo em seus peitos.' },
      { v: 8, en: 'But Nineveh has been from of old like a pool of water, yet they flee away. “Stop! Stop!” they cry, but no one looks back.', pt: 'Nínive desde que existe tem sido como um tanque de águas; elas, porém, fogem agora: parai, parai, clama-se; mas ninguém olhara para trás.' },
      { v: 9, en: 'Take the plunder of silver. Take the plunder of gold, for there is no end of the store, the glory of all goodly furniture.', pt: 'Saqueai a prata, saqueai o ouro; pois não ha fim dos tesouros; abastança há de todas as coisas preciosas.' },
      { v: 10, en: 'She is empty, void, and waste. The heart melts, the knees knock together, their bodies and faces have grown pale.', pt: 'Ela está vazia, esgotada e devastada; derrete-se o coração, tremem os joelhos, e em todos os lombos há dor; o rosto de todos eles empalidece.' },
      { v: 11, en: 'Where is the den of the lions, and the feeding place of the young lions, where the lion and the lioness walked, the lion’s cubs, and no one made them afraid?', pt: 'Onde está agora o covil dos leões, e a habitação dos leões novos, onde andavam o leão, e a leoa, e o cachorro do leão, sem haver ninguém que os espantasse?' },
      { v: 12, en: 'The lion tore in pieces enough for his cubs, and strangled for his lionesses, and filled his caves with the kill, and his dens with prey.', pt: 'O leão arrebatava o que bastava para os seus cachorros, e estrangulava a presa para as suas leoas, e enchia de presas as suas cavernas, e de rapina os seus covis.' },
      { v: 13, en: '“Behold, I am against you,” says Yahweh of Armies, “and I will burn her chariots in the smoke, and the sword will devour your young lions; and I will cut off your prey from the earth, and the voice of your messengers will no longer be heard.”', pt: 'Eis que eu estou contra ti, diz o Senhor dos exércitos, e queimarei na fumaça os teus carros, e a espada devorará os teus leões novos; e exterminarei da terra a tua presa; e não se ouvira mais a voz dos teus embaixadores.' },
    ],
    3: [
      { v: 1, en: 'Woe to the bloody city! It is all full of lies and robbery. The prey doesn’t depart.', pt: 'Ai da cidade ensangüentada! Ela está toda cheia de mentiras e de rapina! da presa não há fim!' },
      { v: 2, en: 'The noise of the whip, the noise of the rattling of wheels, prancing horses, and bounding chariots,', pt: 'Eis o estrépito do açoite, e o estrondo das rodas, os cavalos que curveteiam e os carros que saltam;' },
      { v: 3, en: 'the horseman mounting, and the flashing sword, the glittering spear, and a multitude of slain, and a great heap of corpses, and there is no end of the bodies. They stumble on their bodies,', pt: 'o cavaleiro que monta, a espada rutilante, a lança reluzente, a, multidão de mortos, o montão de cadáveres, e defuntos inumeráveis; tropeçam nos cadáveres;' },
      { v: 4, en: 'because of the multitude of the prostitution of the alluring prostitute, the mistress of witchcraft, who sells nations through her prostitution, and families through her witchcraft.', pt: 'tudo isso por causa da multidão dos adultérios, da meretriz formosa, da mestra das feitiçarias, que vende nações por seus deleites, e familias pelas suas feitiçarias.' },
      { v: 5, en: '“Behold, I am against you,” says Yahweh of Armies, “and I will lift your skirts over your face. I will show the nations your nakedness, and the kingdoms your shame.', pt: 'Eis que eu estou contra ti, diz o Senhor dos exercitos; e levantarei as tuas fraldas sobre a tua face; e às nações mostrarei a tua nudez, e seus reinos a tua vergonha.' },
      { v: 6, en: 'I will throw abominable filth on you, and make you vile, and will set you a spectacle.', pt: 'Lançarei sobre ti imundícias e te tratarei com desprezo, e te porei como espetáculo.' },
      { v: 7, en: 'It will happen that all those who look at you will flee from you, and say, ‘Nineveh is laid waste! Who will mourn for her?’ Where will I seek comforters for you?”', pt: 'E há de ser todos os que te virem fugirão de ti, e dirão: Nínive esta destruída; quem tera compaixão dela? Donde te buscarei consoladores?' },
      { v: 8, en: 'Are you better than No-Amon, who was situated among the rivers, who had the waters around her; whose rampart was the sea, and her wall was of the sea?', pt: 'És tu melhor do que Tebas, que se sentava à beira do Nilo, cercada de águas, tendo por baluarte o mar, e as aguas por muralha,' },
      { v: 9, en: 'Cush and Egypt were her boundless strength. Put and Libya were her helpers.', pt: 'Etiópia e Egito eram a sua força, que era inesgotável; Pute e Líbia eram teus aliados.' },
      { v: 10, en: 'Yet was she carried away. She went into captivity. Her young children also were dashed in pieces at the head of all the streets, and they cast lots for her honorable men, and all her great men were bound in chains.', pt: 'Todavia ela foi levada, foi para o cativeiro; também os seus pequeninos foram despedaçados nas entradas de todas as ruas, e sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos em grilhões.' },
      { v: 11, en: 'You also will be drunken. You will be hidden. You also will seek a stronghold because of the enemy.', pt: 'Tu também serás embriagada, e ficarás escondida; e buscarás um refúgio do inimigo.' },
      { v: 12, en: 'All your fortresses will be like fig trees with the first-ripe figs: if they are shaken, they fall into the mouth of the eater.', pt: 'Todas as tuas fortalezas serão como figueiras com figos temporãos; sendo eles sacudidos, caem na boca do que os há de comer.' },
      { v: 13, en: 'Behold, your troops among you are women. The gates of your land are set wide open to your enemies. The fire has devoured your bars.', pt: 'Eis que as tuas tropas no meio de ti são como mulheres; as portas da tua terra estão de todo abertas aos teus inimigos; o fogo consome os teus ferrolhos.' },
      { v: 14, en: 'Draw water for the siege. Strengthen your fortresses. Go into the clay, and tread the mortar. Make the brick kiln strong.', pt: 'Tira água para o tempo do cerco; reforça as tuas fortalezas; entra no lodo, pisa o barro, pega na forma para os tijolos.' },
      { v: 15, en: 'There the fire will devour you. The sword will cut you off. It will devour you like the grasshopper. Multiply like grasshoppers. Multiply like the locust.', pt: 'O fogo ali te consumirá; a espada te exterminará; ela te devorará como a locusta. Multiplica-te como a locusta, multiplica-te como o gafanhoto.' },
      { v: 16, en: 'You have increased your merchants more than the stars of the skies. The grasshopper strips, and flees away.', pt: 'Multiplicaste os teus negociantes mais do que as estrelas do céu; a locusta estende as asas e sai voando.' },
      { v: 17, en: 'Your guards are like the locusts, and your officials like the swarms of locusts, which settle on the walls on a cold day, but when the sun appears, they flee away, and their place is not known where they are.', pt: 'Os teus príncipes são como os gafanhotos, e os teus chefes como enxames de gafanhotos, que se acampam nas sebes nos dias de frio; em subindo o sol voam, e não se sabe o lugar em que estão.' },
      { v: 18, en: 'Your shepherds slumber, king of Assyria. Your nobles lie down. Your people are scattered on the mountains, and there is no one to gather them.', pt: 'Os teus pastores dormitam, ó rei da Assíria; os teus nobres dormem, o teu povo está espalhado pelos montes, sem que haja quem o ajunte.' },
      { v: 19, en: 'There is no healing your wound, for your injury is fatal. All who hear the report of you clap their hands over you; for who hasn’t felt your endless cruelty?', pt: 'Não há cura para a tua ferida; a tua chaga é grave. Todos os que ouvirem a tua fama baterão as palmas sobre ti; porque, sobre quem não tem passado continuamente a tua malícia?' },
    ],
  },
};

export default book;
