import type { BibleBook } from '../bibleData';

export const proverbsBook: BibleBook = {
  id: 'proverbs',
  name: 'Provérbios',
  englishName: 'Proverbs',
  testament: 'old',
  chapters: {
    1: [
      { v: 1,  en: 'The proverbs of Solomon the son of David, king of Israel;', pt: 'Os provérbios de Salomão, filho de Davi, rei de Israel,' },
      { v: 2,  en: 'To know wisdom and instruction; to perceive the words of understanding;', pt: 'Para se conhecer a sabedoria e a instrução, para se entenderem as palavras de prudência;' },
      { v: 3,  en: 'To receive the instruction of wisdom, justice, and judgment, and equity;', pt: 'Para se receber a instrução da sabedoria, da justiça, do juízo e da equidade;' },
      { v: 4,  en: 'To give subtilty to the simple, to the young man knowledge and discretion.', pt: 'Para dar sagacidade aos simples, ao jovem conhecimento e discrição.' },
      { v: 5,  en: 'A wise man will hear, and will increase learning; and a man of understanding shall attain unto wise counsels:', pt: 'O sábio ouvirá e crescerá em conhecimento, e o homem entendido adquirirá sábia direção,' },
      { v: 6,  en: 'To understand a proverb, and the interpretation; the words of the wise, and their dark sayings.', pt: 'Para entender um provérbio e a sua interpretação, as palavras dos sábios e os seus enigmas.' },
      { v: 7,  en: 'The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.', pt: 'O temor do Senhor é o princípio da sabedoria; os loucos desprezam a sabedoria e a instrução.' },
      { v: 8,  en: 'My son, hear the instruction of thy father, and forsake not the law of thy mother:', pt: 'Filho meu, ouve a instrução de teu pai e não abandones a lei de tua mãe;' },
      { v: 9,  en: 'For they shall be an ornament of grace unto thy head, and chains about thy neck.', pt: 'Porque serão diadema de graça à tua cabeça e colares ao teu pescoço.' },
      { v: 10, en: 'My son, if sinners entice thee, consent thou not.', pt: 'Filho meu, se os pecadores te quiserem persuadir, não consintas.' },
      { v: 20, en: 'Wisdom crieth without; she uttereth her voice in the streets:', pt: 'A sabedoria clama lá fora; nas praças ela alça a sua voz;' },
      { v: 22, en: 'How long, ye simple ones, will ye love simplicity? and the scorners delight in their scorning, and fools hate knowledge?', pt: 'Até quando, ó simples, amareis a simplicidade? E os escarnecedores se deleitarão no escárnio? E os loucos odiarão o conhecimento?' },
      { v: 23, en: 'Turn you at my reproof: behold, I will pour out my spirit unto you, I will make known my words unto you.', pt: 'Convertei-vos à minha repreensão; eis que eu vos derramarei o meu espírito e vos farei conhecer as minhas palavras.' },
      { v: 33, en: 'But whoso hearkeneth unto me shall dwell safely, and shall be quiet from fear of evil.', pt: 'Mas quem me ouvir habitará em segurança e estará sossegado, sem temor do mal.' },
    ],
    2: [
      { v: 1,  en: 'My son, if thou wilt receive my words, and hide my commandments with thee;', pt: 'Filho meu, se receberes as minhas palavras e esconderes contigo os meus mandamentos,' },
      { v: 2,  en: 'So that thou incline thine ear unto wisdom, and apply thine heart to understanding;', pt: 'De modo que apliques à sabedoria o teu ouvido e inclines o teu coração ao entendimento;' },
      { v: 3,  en: 'Yea, if thou criest after knowledge, and liftest up thy voice for understanding;', pt: 'Sim, se clamares pela inteligência e pela compreensão elevares a voz;' },
      { v: 4,  en: 'If thou seekest her as silver, and searchest for her as for hid treasures;', pt: 'Se buscares como prata e como tesouros escondidos a procurares;' },
      { v: 5,  en: 'Then shalt thou understand the fear of the LORD, and find the knowledge of God.', pt: 'Então entenderás o temor do Senhor e acharás o conhecimento de Deus.' },
      { v: 6,  en: 'For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.', pt: 'Porque o Senhor dá a sabedoria; da sua boca procedem o conhecimento e o entendimento.' },
      { v: 7,  en: 'He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly.', pt: 'Ele reserva a verdadeira sabedoria para os retos; é escudo para os que caminham em integridade.' },
      { v: 10, en: 'When wisdom entereth into thine heart, and knowledge is pleasant unto thy soul;', pt: 'Quando a sabedoria entrar no teu coração e o conhecimento for agradável à tua alma,' },
      { v: 11, en: 'Discretion shall preserve thee, understanding shall keep thee:', pt: 'A discrição te guardará e o entendimento te conservará,' },
    ],
    3: [
      { v: 1,  en: 'My son, forget not my law; but let thine heart keep my commandments:', pt: 'Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos;' },
      { v: 2,  en: 'For length of days, and long life, and peace, shall they add to thee.', pt: 'Porque eles prolongarão os dias, anos de vida e paz te acrescentarão.' },
      { v: 3,  en: 'Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:', pt: 'Não te abandonem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração.' },
      { v: 4,  en: 'So shalt thou find favour and good understanding in the sight of God and man.', pt: 'Assim acharás graça e boa compreensão aos olhos de Deus e dos homens.' },
      { v: 5,  en: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', pt: 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.' },
      { v: 6,  en: 'In all thy ways acknowledge him, and he shall direct thy paths.', pt: 'Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.' },
      { v: 7,  en: 'Be not wise in thine own eyes: fear the LORD, and depart from evil.', pt: 'Não sejas sábio aos teus próprios olhos; teme o Senhor e aparta-te do mal.' },
      { v: 8,  en: 'It shall be health to thy navel, and marrow to thy bones.', pt: 'Isso será saúde para o teu corpo e refrigério para os teus ossos.' },
      { v: 9,  en: 'Honour the LORD with thy substance, and with the firstfruits of all thine increase:', pt: 'Honra ao Senhor com os teus bens e com as primícias de todos os teus rendimentos.' },
      { v: 10, en: 'So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.', pt: 'Assim se encherão os teus celeiros de abundância, e os teus lagares transbordarão de mosto.' },
      { v: 11, en: 'My son, despise not the chastening of the LORD; neither be weary of his correction:', pt: 'Filho meu, não rejeites a disciplina do Senhor nem te fatigues com a sua repreensão;' },
      { v: 12, en: 'For whom the LORD loveth he correcteth; even as a father the son in whom he delighteth.', pt: 'Porque o Senhor repreende aquele que ama, como o pai ao filho em quem tem prazer.' },
      { v: 13, en: 'Happy is the man that findeth wisdom, and the man that getteth understanding.', pt: 'Bem-aventurado o homem que acha a sabedoria e o homem que adquire o entendimento.' },
      { v: 14, en: 'For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold.', pt: 'Porque é melhor o lucro que ela dá do que o da prata, e o seu ganho é maior do que o do ouro mais fino.' },
      { v: 15, en: 'She is more precious than rubies: and all the things thou canst desire are not to be compared unto her.', pt: 'É mais preciosa do que os rubis, e tudo o que podes desejar não se pode comparar a ela.' },
      { v: 16, en: 'Length of days is in her right hand; and in her left hand riches and honour.', pt: 'Longura de dias está na sua mão direita; na sua mão esquerda, riquezas e honras.' },
      { v: 17, en: 'Her ways are ways of pleasantness, and all her paths are peace.', pt: 'Os seus caminhos são caminhos de prazer e todas as suas veredas são de paz.' },
      { v: 18, en: 'She is a tree of life to them that lay hold upon her: and happy is every one that retaineth her.', pt: 'É árvore de vida para os que a abraçam, e bem-aventurado é todo aquele que a retém.' },
      { v: 19, en: 'The LORD by wisdom hath founded the earth; by understanding hath he established the heavens.', pt: 'O Senhor com sabedoria fundou a terra; com entendimento estabeleceu os céus.' },
      { v: 24, en: 'When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet.', pt: 'Quando te deitares, não terás medo; quando te recolheres, o teu sono será suave.' },
      { v: 25, en: 'Be not afraid of sudden fear, neither of the desolation of the wicked, when it cometh.', pt: 'Não terás medo do terror repentino nem da desolação dos ímpios, quando vier.' },
      { v: 26, en: 'For the LORD shall be thy confidence, and shall keep thy foot from being taken.', pt: 'Porque o Senhor será a tua confiança e guardará o teu pé de ser apanhado.' },
    ],
    4: [
      { v: 1,  en: 'Hear, ye children, the instruction of a father, and attend to know understanding.', pt: 'Ouvi, filhos, a instrução do pai e prestai atenção para conhecerdes o entendimento.' },
      { v: 5,  en: 'Get wisdom, get understanding: forget it not; neither decline from the words of my mouth.', pt: 'Adquire a sabedoria, adquire o entendimento; não te esqueças nem te apartes das palavras da minha boca.' },
      { v: 6,  en: 'Forsake her not, and she shall preserve thee: love her, and she shall keep thee.', pt: 'Não a abandones, e ela te guardará; ama-a, e ela te conservará.' },
      { v: 7,  en: 'Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.', pt: 'O principal é a sabedoria; adquire, pois, a sabedoria; sim, com tudo o que possuis adquire o entendimento.' },
      { v: 18, en: 'But the path of the just is as the shining light, that shineth more and more unto the perfect day.', pt: 'Mas a vereda dos justos é como a luz da aurora, que vai brilhando mais e mais até ser dia perfeito.' },
      { v: 19, en: 'The way of the wicked is as darkness: they know not at what they stumble.', pt: 'O caminho dos ímpios é como as trevas; eles não sabem em que tropeçam.' },
      { v: 23, en: 'Keep thy heart with all diligence; for out of it are the issues of life.', pt: 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as origens da vida.' },
    ],
    5: [
      { v: 1,  en: 'My son, attend unto my wisdom, and bow thine ear to my understanding:', pt: 'Filho meu, atenta à minha sabedoria; inclina o teu ouvido ao meu entendimento,' },
      { v: 2,  en: 'That thou mayest regard discretion, and that thy lips may keep knowledge.', pt: 'Para que guardes a discrição e os teus lábios conservem o conhecimento.' },
      { v: 3,  en: 'For the lips of a strange woman drop as an honeycomb, and her mouth is smoother than oil:', pt: 'Porque os lábios da mulher estranha destilam mel, e o seu falar é mais suave do que o azeite;' },
      { v: 4,  en: 'But her end is bitter as wormwood, sharp as a twoedged sword.', pt: 'Mas o seu fim é amargo como o absinto, agudo como espada de dois gumes.' },
      { v: 5,  en: 'Her feet go down to death; her steps take hold on hell.', pt: 'Os seus pés descem para a morte; os seus passos chegam até ao inferno.' },
      { v: 7,  en: 'Hear me now therefore, O ye children, and depart not from the words of my mouth.', pt: 'Ora, filhos, ouvi-me e não vos aparteis das palavras da minha boca.' },
      { v: 8,  en: 'Remove thy way far from her, and come not nigh the door of her house:', pt: 'Afasta dela o teu caminho e não chegues à porta da sua casa;' },
      { v: 15, en: 'Drink waters out of thine own cistern, and running waters out of thine own well.', pt: 'Bebe água da tua própria cisterna e as correntes do teu próprio poço.' },
      { v: 18, en: 'Let thy fountain be blessed: and rejoice with the wife of thy youth.', pt: 'Seja bendita a tua fonte, e alegra-te com a mulher da tua mocidade.' },
      { v: 19, en: 'Let her be as the loving hind and pleasant roe; let her breasts satisfy thee at all times; and be thou ravished always with her love.', pt: 'Como corça amorosa e agradável gazela; os seus seios te satisfaçam em todo tempo; e pelo seu amor sejas atraído sempre.' },
      { v: 21, en: 'For the ways of man are before the eyes of the LORD, and he pondereth all his goings.', pt: 'Porque os caminhos do homem estão ante os olhos do Senhor, e ele pondera todas as suas veredas.' },
      { v: 22, en: 'His own iniquities shall take the wicked himself, and he shall be holden with the cords of his sins.', pt: 'As suas próprias iniquidades prenderão o ímpio; e será retido com as cordas do seu pecado.' },
      { v: 23, en: 'He shall die without instruction; and in the greatness of his folly he shall go astray.', pt: 'Morrerá por falta de instrução, e na grandeza da sua loucura se perderá.' },
    ],
    6: [
      { v: 6,  en: 'Go to the ant, thou sluggard; consider her ways, and be wise:', pt: 'Vai ter com a formiga, ó preguiçoso; considera os seus caminhos e sê sábio.' },
      { v: 7,  en: 'Which having no guide, overseer, or ruler,', pt: 'Ela, que não tem capitão, nem feitor, nem senhor,' },
      { v: 8,  en: 'Provideth her meat in the summer, and gathereth her food in the harvest.', pt: 'Prepara no verão a sua comida e ajunta na sega o seu mantimento.' },
      { v: 9,  en: 'How long wilt thou sleep, O sluggard? when wilt thou arise out of thy sleep?', pt: 'Até quando dormirás, ó preguiçoso? Quando te levantarás do teu sono?' },
      { v: 16, en: 'These six things doth the LORD hate: yea, seven are an abomination unto him:', pt: 'Seis coisas há que o Senhor aborrece e sete são abominação para ele:' },
      { v: 17, en: 'A proud look, a lying tongue, and hands that shed innocent blood,', pt: 'Os olhos altivos, a língua mentirosa e as mãos que derramam sangue inocente,' },
      { v: 18, en: 'An heart that deviseth wicked imaginations, feet that be swift in running to mischief,', pt: 'O coração que maquina pensamentos iníquos, os pés que se apressam a correr para o mal,' },
      { v: 19, en: 'A false witness that speaketh lies, and he that soweth discord among brethren.', pt: 'A testemunha falsa que profere mentiras e aquele que semeia contendas entre irmãos.' },
    ],
    7: [
      { v: 1,  en: 'My son, keep my words, and lay up my commandments with thee.', pt: 'Filho meu, guarda as minhas palavras e entesourares contigo os meus mandamentos.' },
      { v: 2,  en: 'Keep my commandments, and live; and my law as the apple of thine eye.', pt: 'Guarda os meus mandamentos e viverás; e a minha lei como a menina dos teus olhos.' },
      { v: 3,  en: 'Bind them upon thy fingers, write them upon the table of thine heart.', pt: 'Ata-os nos teus dedos; escreve-os na tábua do teu coração.' },
      { v: 4,  en: 'Say unto wisdom, Thou art my sister; and call understanding thy kinswoman:', pt: 'Dize à sabedoria: Tu és minha irmã; e chama ao entendimento teu parente próximo;' },
      { v: 5,  en: 'That they may keep thee from the strange woman, from the stranger which flattereth with her words.', pt: 'Para que te guardem da mulher estranha, da estranha que lisonjeia com as suas palavras.' },
      { v: 24, en: 'Hearken unto me now therefore, O ye children, and attend to the words of my mouth.', pt: 'Ora pois, filhos, ouvi-me, e estai atentos às palavras da minha boca.' },
      { v: 25, en: 'Let not thine heart decline to her ways, go not astray in her paths.', pt: 'Não se incline o teu coração para os seus caminhos; não te extravies pelas suas veredas.' },
      { v: 26, en: 'For she hath cast down many wounded: yea, many strong men have been slain by her.', pt: 'Porque ela tem abatido muitos feridos; e todos os que ela matou eram fortes.' },
      { v: 27, en: 'Her house is the way to hell, going down to the chambers of death.', pt: 'A sua casa é o caminho para o inferno, que desce às câmaras da morte.' },
    ],
    8: [
      { v: 1,  en: 'Doth not wisdom cry? and understanding put forth her voice?', pt: 'Porventura não clama a sabedoria? E não levanta a sua voz o entendimento?' },
      { v: 10, en: 'Receive my instruction, and not silver; and knowledge rather than choice gold.', pt: 'Recebei a minha instrução, e não a prata, e o conhecimento antes do ouro mais fino.' },
      { v: 11, en: 'For wisdom is better than rubies; and all the things that may be desired are not to be compared to it.', pt: 'Porque a sabedoria é melhor do que os rubis; e tudo o que se pode desejar não se compara a ela.' },
      { v: 12, en: 'I wisdom dwell with prudence, and find out knowledge of witty inventions.', pt: 'Eu, a Sabedoria, habito com a prudência e encontro o conhecimento e a discrição.' },
      { v: 13, en: 'The fear of the LORD is to hate evil: pride, and arrogancy, and the evil way, and the froward mouth, do I hate.', pt: 'O temor do Senhor é aborrecer o mal; eu aborreço o orgulho e a soberba e o caminho mau e a boca perversa.' },
      { v: 14, en: 'Counsel is mine, and sound wisdom: I am understanding; I have strength.', pt: 'Meus são o conselho e a sã sabedoria; eu sou a inteligência; minha é a força.' },
      { v: 17, en: 'I love them that love me; and those that seek me early shall find me.', pt: 'Eu amo os que me amam, e os que me procuram me acharão.' },
      { v: 22, en: 'The LORD possessed me at the beginning of his work, the first of his acts of old.', pt: 'O Senhor me possuía no princípio do seu caminho, antes das suas obras antigas.' },
      { v: 35, en: 'For whoso findeth me findeth life, and shall obtain favour of the LORD.', pt: 'Pois quem me achar achará a vida e obterá a graça do Senhor.' },
      { v: 36, en: 'But he that sinneth against me wrongeth his own soul: all they that hate me love death.', pt: 'Mas o que pecar contra mim causará dano à própria alma; todos os que me odeiam amam a morte.' },
    ],
    9: [
      { v: 10, en: 'The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.', pt: 'O temor do Senhor é o princípio da sabedoria e o conhecimento do Santo é o entendimento.' },
    ],
    10: [
      { v: 1,  en: 'The proverbs of Solomon. A wise son maketh a glad father: but a foolish son is the heaviness of his mother.', pt: 'Os provérbios de Salomão. O filho sábio alegra o pai; mas o filho insensato é a tristeza de sua mãe.' },
      { v: 2,  en: 'Treasures of wickedness profit nothing: but righteousness delivereth from death.', pt: 'Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.' },
      { v: 4,  en: 'He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich.', pt: 'Empobrece o que trabalha com mão preguiçosa; mas a mão dos diligentes enriquece.' },
      { v: 7,  en: 'The memory of the just is blessed: but the name of the wicked shall rot.', pt: 'A memória do justo é com bênçãos; mas o nome dos ímpios apodrecerá.' },
      { v: 8,  en: 'The wise in heart will receive commandments: but a prating fool shall fall.', pt: 'O sábio de coração receberá mandamentos; mas o louco de lábios terá queda.' },
      { v: 11, en: 'The mouth of a righteous man is a well of life: but violence covereth the mouth of the wicked.', pt: 'A boca do justo é fonte de vida; mas a boca dos ímpios encobre a violência.' },
      { v: 12, en: 'Hatred stirreth up strifes: but love covereth all sins.', pt: 'O ódio excita contendas; mas o amor cobre todas as transgressões.' },
      { v: 17, en: 'He is in the way of life that keepeth instruction: but he that refuseth reproof erreth.', pt: 'O que guarda a instrução está no caminho da vida; mas o que abandona a repreensão erra.' },
      { v: 19, en: 'In the multitude of words there wanteth not sin: but he that refraineth his lips is wise.', pt: 'Na multidão das palavras não faltará o pecado; mas o que refreia os seus lábios é prudente.' },
      { v: 22, en: 'The blessing of the LORD, it maketh rich, and he addeth no sorrow with it.', pt: 'A bênção do Senhor enriquece, e não acarreta tristeza.' },
    ],
    11: [
      { v: 1,  en: 'A false balance is abomination to the LORD: but a just weight is his delight.', pt: 'A balança falsa é abominação ao Senhor; mas o peso justo é o seu contentamento.' },
      { v: 2,  en: 'When pride cometh, then cometh shame: but with the lowly is wisdom.', pt: 'Quando vem a soberba, vem também a vergonha; mas com os humildes está a sabedoria.' },
      { v: 3,  en: 'The integrity of the upright shall guide them: but the perverseness of transgressors shall destroy them.', pt: 'A integridade dos retos os guia; mas a perversidade dos aleivosos os destrói.' },
      { v: 14, en: 'Where no counsel is, the people fall: but in the multitude of counsellors there is safety.', pt: 'Onde não há sábia direção, o povo cai; mas na multidão de conselheiros há segurança.' },
      { v: 24, en: 'There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty.', pt: 'Há quem distribua e fique com mais; e há quem retenha mais do que é justo, mas apenas para a sua pobreza.' },
      { v: 25, en: 'The liberal soul shall be made fat: and he that watereth shall be watered also himself.', pt: 'A alma generosa prosperará; e quem abasta os outros será também ele fartado.' },
      { v: 28, en: 'He that trusteth in his riches shall fall: but the righteous shall flourish as a branch.', pt: 'O que confia nas suas riquezas cairá; mas os justos reverdecerão como a folhagem.' },
      { v: 30, en: 'The fruit of the righteous is a tree of life; and he that winneth souls is wise.', pt: 'O fruto do justo é árvore de vida; e o que ganha almas é sábio.' },
    ],
    12: [
      { v: 1,  en: 'Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish.', pt: 'O que ama a instrução ama o conhecimento; mas o que odeia a repreensão é estúpido.' },
      { v: 15, en: 'The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.', pt: 'O caminho do tolo parece reto aos seus próprios olhos; mas o que ouve conselhos é sábio.' },
      { v: 17, en: 'An honest witness delivereth just testimony: but a false witness speaketh deceit.', pt: 'O que diz a verdade declara o que é justo; mas a testemunha falsa profere engano.' },
      { v: 18, en: 'There is that speaketh like the piercings of a sword: but the tongue of the wise is health.', pt: 'Há palavras que ferem como golpes de espada; mas a língua dos sábios é medicina.' },
    ],
    13: [
      { v: 1,  en: 'A wise son heareth his father\'s instruction: but a scorner heareth not rebuke.', pt: 'O filho sábio ouve a instrução do pai; mas o escarnecedor não ouve a repreensão.' },
      { v: 11, en: 'Wealth gotten by vanity shall be diminished: but he that gathereth by labour shall increase.', pt: 'A riqueza obtida às pressas diminuirá; mas o que a ajunta pouco a pouco a aumentará.' },
      { v: 12, en: 'Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life.', pt: 'A esperança que se prolonga enoja o coração; mas o desejo cumprido é árvore de vida.' },
      { v: 20, en: 'He that walketh with wise men shall be wise: but a companion of fools shall be destroyed.', pt: 'O que anda com os sábios será sábio; mas o companheiro dos insensatos sofrerá dano.' },
    ],
    14: [
      { v: 12, en: 'There is a way which seemeth right unto a man, but the end thereof are the ways of death.', pt: 'Há um caminho que parece reto ao homem, mas o seu fim são os caminhos da morte.' },
      { v: 26, en: 'In the fear of the LORD is strong confidence: and his children shall have a place of refuge.', pt: 'No temor do Senhor há forte confiança, e os seus filhos terão um lugar de refúgio.' },
      { v: 27, en: 'The fear of the LORD is a fountain of life, to depart from the snares of death.', pt: 'O temor do Senhor é fonte de vida para desviar das ciladas da morte.' },
      { v: 29, en: 'He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly.', pt: 'O que é tarde em irar-se tem muito entendimento; mas o impaciente exalta a loucura.' },
      { v: 34, en: 'Righteousness exalteth a nation: but sin is a reproach to any people.', pt: 'A justiça exalta uma nação; mas o pecado é a vergonha dos povos.' },
    ],
    15: [
      { v: 1,  en: 'A soft answer turneth away wrath: but grievous words stir up anger.', pt: 'A resposta branda desvia o furor; mas as palavras duras excitam a ira.' },
      { v: 2,  en: 'The tongue of the wise useth knowledge aright: but the mouth of fools poureth out foolishness.', pt: 'A língua dos sábios usa acertadamente o conhecimento; mas a boca dos loucos transborda de loucura.' },
      { v: 3,  en: 'The eyes of the LORD are in every place, beholding the evil and the good.', pt: 'Os olhos do Senhor estão em todo o lugar, contemplando os maus e os bons.' },
      { v: 13, en: 'A merry heart maketh a cheerful countenance: but by sorrow of the heart the spirit is broken.', pt: 'O coração alegre aformoseia o semblante; mas pela dor do coração o espírito se abate.' },
      { v: 15, en: 'All the days of the afflicted are evil: but he that is of a merry heart hath a continual feast.', pt: 'Todos os dias do aflito são maus; mas o alegre de coração tem um banquete contínuo.' },
      { v: 16, en: 'Better is little with the fear of the LORD than great treasure and trouble therewith.', pt: 'Melhor é o pouco com o temor do Senhor do que o grande tesouro onde há inquietação.' },
      { v: 17, en: 'Better is a dinner of herbs where love is, than a stalled ox and hatred therewith.', pt: 'Melhor é um prato de ervas com amor do que o boi cevado com ódio.' },
      { v: 22, en: 'Without counsel purposes are disappointed: but in the multitude of counsellors they are established.', pt: 'Os propósitos fracassam onde não há conselho; mas com muitos conselheiros se firmam.' },
      { v: 33, en: 'The fear of the LORD is the instruction of wisdom; and before honour is humility.', pt: 'O temor do Senhor é instrução da sabedoria; e antes da honra vai a humildade.' },
    ],
    16: [
      { v: 3,  en: 'Commit thy works unto the LORD, and thy thoughts shall be established.', pt: 'Confia ao Senhor as tuas obras, e os teus projetos se firmarão.' },
      { v: 7,  en: 'When a man\'s ways please the LORD, he maketh even his enemies to be at peace with him.', pt: 'Quando os caminhos do homem agradam ao Senhor, até os seus inimigos ele reconcilia com ele.' },
      { v: 9,  en: 'A man\'s heart deviseth his way: but the LORD directeth his steps.', pt: 'O coração do homem planeja o seu caminho; mas o Senhor lhe dirige os passos.' },
      { v: 16, en: 'How much better is it to get wisdom than gold! and to get understanding rather to be chosen than silver!', pt: 'Quanto melhor é adquirir a sabedoria do que o ouro! E adquirir o entendimento é preferível à prata!' },
      { v: 18, en: 'Pride goeth before destruction, and an haughty spirit before a fall.', pt: 'A soberba precede a ruína, e a altivez de espírito precede a queda.' },
      { v: 19, en: 'Better it is to be of an humble spirit with the lowly, than to divide the spoil with the proud.', pt: 'Melhor é ser humilde de espírito com os pobres do que repartir os despojos com os soberbos.' },
      { v: 20, en: 'He that handleth a matter wisely shall find good: and whoso trusteth in the LORD, happy is he.', pt: 'O que atende à palavra acha o bem; e o que confia no Senhor é bem-aventurado.' },
      { v: 24, en: 'Pleasant words are as an honeycomb, sweet to the soul, and health to the bones.', pt: 'As palavras agradáveis são como o favo de mel, doces para a alma e saúde para os ossos.' },
      { v: 32, en: 'He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.', pt: 'Melhor é o que é tardio em irar-se do que o poderoso; e o que governa o seu espírito do que o que toma uma cidade.' },
    ],
    17: [
      { v: 1,  en: 'Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife.', pt: 'Melhor é um bocado seco e com ele quietação do que uma casa cheia de sacrifícios com contenda.' },
      { v: 17, en: 'A friend loveth at all times, and a brother is born for adversity.', pt: 'Em todo o tempo ama o amigo; e para a hora da angústia nasce um irmão.' },
      { v: 22, en: 'A merry heart doeth good like a medicine: but a broken spirit drieth the bones.', pt: 'O coração alegre é um bom remédio; mas o espírito abatido seca os ossos.' },
    ],
    18: [
      { v: 10, en: 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.', pt: 'O nome do Senhor é uma torre forte; para ela corre o justo e está seguro.' },
      { v: 22, en: 'Whoso findeth a wife findeth a good thing, and obtaineth favour of the LORD.', pt: 'Aquele que acha esposa acha um bem e obtém a graça do Senhor.' },
      { v: 24, en: 'A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother.', pt: 'O homem que tem amigos deve mostrar-se amigo; e há um amigo mais chegado do que um irmão.' },
    ],
    19: [
      { v: 11, en: 'The discretion of a man deferreth his anger; and it is his glory to pass over a transgression.', pt: 'A prudência do homem refreia o seu furor, e sua glória é perdoar a ofensa.' },
      { v: 17, en: 'He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again.', pt: 'O que tem misericórdia do pobre empresta ao Senhor; e ele lhe retribuirá o bem que fez.' },
      { v: 20, en: 'Hear counsel, and receive instruction, that thou mayest be wise in thy latter end.', pt: 'Ouve o conselho e recebe a instrução para que sejas sábio no tempo futuro.' },
      { v: 21, en: 'There are many devices in a man\'s heart; nevertheless the counsel of the LORD, that shall stand.', pt: 'Muitos são os projetos no coração do homem; mas o conselho do Senhor permanecerá.' },
    ],
    20: [
      { v: 1,  en: 'Wine is a mocker, strong drink is raging: and whosoever is deceived thereby is not wise.', pt: 'O vinho é escarnecedor, a bebida forte é alvoroçadora; e todo aquele que por eles é enganado não é sábio.' },
      { v: 7,  en: 'The just man walketh in his integrity: his children are blessed after him.', pt: 'O justo que anda na sua integridade - bem-aventurados serão seus filhos depois dele.' },
      { v: 27, en: 'The spirit of man is the candle of the LORD, searching all the inward parts of the belly.', pt: 'O espírito do homem é a lâmpada do Senhor, que penetra todas as câmaras interiores.' },
    ],
    21: [
      { v: 1,  en: 'The king\'s heart is in the hand of the LORD, as the rivers of water: he turneth it whithersoever he will.', pt: 'O coração do rei está na mão do Senhor como correntes de água; ele o inclina para onde quer.' },
      { v: 2,  en: 'Every way of a man is right in his own eyes: but the LORD pondereth the hearts.', pt: 'Cada um dos caminhos do homem parece reto aos seus próprios olhos; mas o Senhor pesa os corações.' },
      { v: 3,  en: 'To do justice and judgment is more acceptable to the LORD than sacrifice.', pt: 'Praticar a justiça e o juízo é mais aceitável ao Senhor do que o sacrifício.' },
      { v: 13, en: 'Whoso stoppeth his ears at the cry of the poor, he also shall cry himself, but shall not be heard.', pt: 'O que cierra os ouvidos ao clamor do pobre também clamará e não será ouvido.' },
      { v: 21, en: 'He that followeth after righteousness and mercy findeth life, righteousness, and honour.', pt: 'O que segue a justiça e a bondade achará a vida, a justiça e a honra.' },
      { v: 23, en: 'Whoso keepeth his mouth and his tongue keepeth his soul from troubles.', pt: 'O que guarda a boca e a língua guarda a sua alma das angústias.' },
    ],
    22: [
      { v: 1,  en: 'A good name is rather to be chosen than great riches, and loving favour rather than silver and gold.', pt: 'O bom nome é preferível às grandes riquezas; e a boa graça é melhor do que a prata e o ouro.' },
      { v: 2,  en: 'The rich and poor meet together: the LORD is the maker of them all.', pt: 'O rico e o pobre se encontram; o Senhor fez a ambos.' },
      { v: 4,  en: 'By humility and the fear of the LORD are riches, and honour, and life.', pt: 'A paga da humildade e do temor do Senhor são as riquezas, a honra e a vida.' },
      { v: 6,  en: 'Train up a child in the way he should go: and when he is old, he will not depart from it.', pt: 'Instrui o menino no caminho em que deve andar; e, até quando envelhecer, não se desviará dele.' },
      { v: 9,  en: 'He that hath a bountiful eye shall be blessed; for he giveth of his bread to the poor.', pt: 'O que tem olho benigno será abençoado, porque dá do seu pão ao pobre.' },
    ],
    23: [
      { v: 4,  en: 'Labour not to be rich: cease from thine own wisdom.', pt: 'Não te fatigues em trabalhar para enriquecer; deixa de aplicar nisso a tua perspicácia.' },
      { v: 5,  en: 'Wilt thou set thine eyes upon that which is not? for riches certainly make themselves wings; they fly away as an eagle toward heaven.', pt: 'Pores os teus olhos naquilo que não é nada? Porque as riquezas certamente fazem para si asas, e, como a águia, voam para o céu.' },
      { v: 15, en: 'My son, if thine heart be wise, my heart shall rejoice, even mine.', pt: 'Filho meu, se o teu coração for sábio, o meu coração se alegrará; sim, o meu mesmo.' },
      { v: 17, en: 'Let not thine heart envy sinners: but be thou in the fear of the LORD all the day long.', pt: 'Não inveje o teu coração os pecadores; antes esteja todo o dia no temor do Senhor.' },
      { v: 22, en: 'Hearken unto thy father that begat thee, and despise not thy mother when she is old.', pt: 'Ouve a teu pai, que te gerou; e não desprezes a tua mãe quando ela envelhecer.' },
      { v: 23, en: 'Buy the truth, and sell it not; also wisdom, and instruction, and understanding.', pt: 'Compra a verdade e não a vendas; também a sabedoria, e a instrução, e o entendimento.' },
      { v: 24, en: 'The father of the righteous shall greatly rejoice: and he that begetteth a wise child shall have joy of him.', pt: 'O pai do justo se alegrará muito; e o que gera um filho sábio se alegra nele.' },
    ],
    24: [
      { v: 3,  en: 'Through wisdom is an house builded; and by understanding it is established:', pt: 'Com sabedoria se edifica a casa; e com o entendimento se consolida.' },
      { v: 4,  en: 'And by knowledge shall the chambers be filled with all precious and pleasant riches.', pt: 'E com a ciência se enchem os aposentos de toda preciosa e aprazível riqueza.' },
      { v: 10, en: 'If thou faint in the day of adversity, thy strength is small.', pt: 'Se te mostrares fraco no dia da adversidade, a tua força é diminuta.' },
      { v: 16, en: 'For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief.', pt: 'Porque o justo cai sete vezes, e torna a levantar-se; mas os ímpios tropeçam na calamidade.' },
    ],
    25: [
      { v: 11, en: 'A word fitly spoken is like apples of gold in pictures of silver.', pt: 'A palavra falada a seu tempo é como maçãs de ouro em salvas de prata.' },
      { v: 15, en: 'By long forbearing is a prince persuaded, and a soft tongue breaketh the bone.', pt: 'Com longanimidade se convence o governante, e a língua branda quebra o osso.' },
      { v: 16, en: 'Hast thou found honey? eat so much as is sufficient for thee, lest thou be filled therewith, and vomit it.', pt: 'Achaste mel? Come o que basta; não te sacies dele, para que não te enjoes.' },
      { v: 21, en: 'If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink:', pt: 'Se o teu inimigo tiver fome, dá-lhe pão para comer; e, se tiver sede, dá-lhe água para beber;' },
      { v: 22, en: 'For thou shalt heap coals of fire upon his head, and the LORD shall reward thee.', pt: 'Porque assim amontoarás brasas sobre a sua cabeça, e o Senhor te retribuirá.' },
    ],
    26: [
      { v: 11, en: 'As a dog returneth to his vomit, so a fool returneth to his folly.', pt: 'Como o cão que volta ao seu próprio vômito, assim é o louco que repete a sua loucura.' },
    ],
    27: [
      { v: 1,  en: 'Boast not thyself of to morrow; for thou knowest not what a day may bring forth.', pt: 'Não te glories do dia de amanhã; porque não sabes o que ele trará.' },
      { v: 2,  en: 'Let another man praise thee, and not thine own mouth; a stranger, and not thine own lips.', pt: 'Que outro te louve, e não a tua própria boca; o estrangeiro, e não os teus próprios lábios.' },
      { v: 17, en: 'Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.', pt: 'O ferro se aguça com o ferro; assim o homem aguça o rosto do seu amigo.' },
    ],
    28: [
      { v: 1,  en: 'The wicked flee when no man pursueth: but the righteous are bold as a lion.', pt: 'O ímpio foge sem que ninguém o persiga; mas o justo é ousado como um leão.' },
      { v: 6,  en: 'Better is the poor that walketh in his uprightness, than he that is perverse in his ways, though he be rich.', pt: 'Melhor é o pobre que anda na sua integridade do que o perverso nos seus caminhos, ainda que seja rico.' },
      { v: 13, en: 'He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy.', pt: 'O que encobre as suas transgressões jamais prosperará; mas o que as confessa e abandona alcançará misericórdia.' },
    ],
    29: [
      { v: 1,  en: 'He, that being often reproved hardeneth his neck, shall suddenly be destroyed, and that without remedy.', pt: 'O homem que, sendo muitas vezes repreendido, endurece o pescoço, de repente será destruído sem remédio.' },
      { v: 11, en: 'A fool uttereth all his mind: but a wise man keepeth it in till afterwards.', pt: 'O tolo vaza todo o seu espírito; mas o sábio o modera e o retém.' },
      { v: 18, en: 'Where there is no vision, the people perish: but he that keepeth the law, happy is he.', pt: 'Onde não há visão profética, o povo se desenfreia; mas bem-aventurado é aquele que guarda a lei.' },
      { v: 25, en: 'The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe.', pt: 'O temor do homem armará um laço; mas quem confia no Senhor estará em segurança.' },
    ],
    30: [
      { v: 5,  en: 'Every word of God is pure: he is a shield unto them that put their trust in him.', pt: 'Toda palavra de Deus é pura; ele é escudo para os que nele confiam.' },
      { v: 8,  en: 'Remove far from me vanity and lies: give me neither poverty nor riches; feed me with food convenient for me:', pt: 'Afasta de mim a vaidade e a mentira; não me dês pobreza nem riqueza; alimenta-me com o pão que me é necessário.' },
      { v: 9,  en: 'Lest I be full, and deny thee, and say, Who is the LORD? or lest I be poor, and steal, and take the name of my God in vain.', pt: 'Para que, saciado, não te negue e diga: Quem é o Senhor? Ou que, empobrecido, eu não roube e tome em vão o nome do meu Deus.' },
    ],
    31: [
      { v: 1, en: 'The words of king Lemuel, the prophecy that his mother taught him.', pt: 'As palavras do rei Lemuel; a profecia que lhe ensinou sua mãe.' },
      { v: 2, en: 'What, my son? and what, the son of my womb? and what, the son of my vows?', pt: 'Que te direi, filho meu? Que direi, filho do meu ventre? Que direi, filho dos meus votos?' },
      { v: 3, en: 'Give not thy strength unto women, nor thy ways to that which destroyeth kings.', pt: 'Não dês às mulheres a tua força, nem os teus caminhos ao que destrói reis.' },
      { v: 4, en: 'It is not for kings, O Lemuel, it is not for kings to drink wine; nor for princes strong drink:', pt: 'Não é dos reis, ó Lemuel, não é dos reis beber vinho; nem dos príncipes desejar bebida forte,' },
      { v: 5, en: 'Lest they drink, and forget the law, and pervert the judgment of any of the afflicted.', pt: 'Para que não bebam e se esqueçam da lei, e pervertam o juízo de todos os aflitos.' },
      { v: 6, en: 'Give strong drink unto him that is ready to perish, and wine unto those that be of heavy hearts.', pt: 'Dai bebida forte ao que está prestes a perecer, e vinho aos de amargo coração.' },
      { v: 7, en: 'Let him drink, and forget his poverty, and remember his misery no more.', pt: 'Beba, e se esqueça da sua pobreza, e não mais se lembre da sua miséria.' },
      { v: 8, en: 'Open thy mouth for the dumb in the cause of all such as are appointed to destruction.', pt: 'Abre a boca pelo mudo, pela causa de todos os que são designados à destruição.' },
      { v: 9, en: 'Open thy mouth, judge righteously, and plead the cause of the poor and needy.', pt: 'Abre a boca, julga retamente, e faze justiça ao pobre e ao necessitado.' },
      { v: 10, en: 'Who can find a virtuous woman? for her price is far above rubies.', pt: 'Mulher virtuosa, quem a achará? O seu valor muito excede o de rubis.' },
      { v: 11, en: 'The heart of her husband doth safely trust in her, so that he shall have no need of spoil.', pt: 'O coração do seu marido confia nela, e não lhe faltará ganho.' },
      { v: 12, en: 'She will do him good and not evil all the days of her life.', pt: 'Ela lhe faz bem e não mal todos os dias da sua vida.' },
      { v: 13, en: 'She seeketh wool, and flax, and worketh willingly with her hands.', pt: 'Busca lã e linho, e trabalha com prazer com as suas mãos.' },
      { v: 14, en: 'She is like the merchants\' ships; she bringeth her food from afar.', pt: 'É como o navio dos mercadores; traz o seu pão de longe.' },
      { v: 15, en: 'She riseth also while it is yet night, and giveth meat to her household, and a portion to her maidens.', pt: 'Levanta-se, quando ainda é noite, e dá mantimento à sua casa, e a tarefa às suas servas.' },
      { v: 16, en: 'She considereth a field, and buyeth it: with the fruit of her hands she planteth a vineyard.', pt: 'Examina uma propriedade, e compra-a; com os frutos do seu trabalho planta uma vinha.' },
      { v: 17, en: 'She girdeth her loins with strength, and strengtheneth her arms.', pt: 'Cinge os seus lombos de força, e fortifica os seus braços.' },
      { v: 18, en: 'She perceiveth that her merchandise is good: her candle goeth not out by night.', pt: 'Percebe que o seu ganho é bom; a sua candeia não se apaga de noite.' },
      { v: 19, en: 'She layeth her hands to the spindle, and her hands hold the distaff.', pt: 'Estende as suas mãos ao fuso, e as suas mãos pegam na roca.' },
      { v: 20, en: 'She stretcheth out her hand to the poor; yea, she reacheth forth her hands to the needy.', pt: 'Abre a mão ao pobre; sim, estende as mãos ao necessitado.' },
      { v: 21, en: 'She is not afraid of the snow for her household: for all her household are clothed with scarlet.', pt: 'Não teme a neve pela sua família, porque toda a sua família está vestida de escarlate.' },
      { v: 22, en: 'She maketh herself coverings of tapestry; her clothing is silk and purple.', pt: 'Faz para si cobertas de tapeçaria; o seu vestuário é de seda e de púrpura.' },
      { v: 23, en: 'Her husband is known in the gates, when he sitteth among the elders of the land.', pt: 'Seu marido é conhecido nas portas, quando se assenta com os anciãos da terra.' },
      { v: 24, en: 'She maketh fine linen, and selleth it; and delivereth girdles unto the merchant.', pt: 'Faz panos de linho fino e vende-os; entrega cintos ao mercador.' },
      { v: 25, en: 'Strength and honour are her clothing; and she shall rejoice in time to come.', pt: 'A força e a glória são o seu vestuário; e se alegra no dia futuro.' },
      { v: 26, en: 'She openeth her mouth with wisdom; and in her tongue is the law of kindness.', pt: 'Abre a boca com sabedoria; e a lei da benignidade está na sua língua.' },
      { v: 27, en: 'She looketh well to the ways of her household, and eateth not the bread of idleness.', pt: 'Está atenta ao andamento da sua casa, e não come o pão da preguiça.' },
      { v: 28, en: 'Her children arise up, and call her blessed; her husband also, and he praiseth her.', pt: 'Levantam-se os seus filhos e chamam-na bem-aventurada; o seu marido também a louva.' },
      { v: 29, en: 'Many daughters have done virtuously, but thou excellest them all.', pt: 'Muitas filhas têm procedido virtuosamente, mas tu sobrepujaste a todas.' },
      { v: 30, en: 'Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised.', pt: 'A graça é enganosa, e a beleza é vaidade; mas a mulher que teme ao Senhor, essa será louvada.' },
      { v: 31, en: 'Give her of the fruit of her hands; and let her own works praise her in the gates.', pt: 'Dai-lhe do fruto das suas mãos, e as suas obras louvem-na nas portas.' },
    ],
  },
};
